["gun_casing"] = {
  usedefaultexplosions = false,

  particlesystem = {
    class = [[CSimpleParticleSystem]],
    count = 1,
    air = true,
    ground = true,
    water = false,
    underwater = false,
    properties = {
      airdrag            = 0.92,
      alwaysvisible      = false,
      colormap           = [[1 0.9 0.6 1   0.6 0.5 0.2 0.8   0.3 0.25 0.1 0.3   0 0 0 0.01]],
      directional        = true,
      emitrot            = 60,
      emitrotspread      = 40,
      emitvector         = [[dir]],
      gravity            = [[0, -0.75, 0]],
      numparticles       = 1,
      particlelife       = 22,
      particlelifespread = 8,
      particlesize       = 1.2,
      particlesizespread = 0.4,
      particlespeed      = 2.8,
      particlespeedspread = 1.2,
      pos                = [[0, 0, 0]],
      sizegrowth         = -0.02,
      sizemod            = 1.0,
      texture            = [[goldshell.png]],
      useairlos          = true,
    },
  },
},