-- bigbulletimpact

return {
  ["smallbulletimpact"] = {

    groundflash = {
      air                = true,
      alwaysvisible      = true,
      circlealpha        = 0.164,
      circlegrowth       = 6,
      flashalpha         = 0.02,
      flashsize          = 15,
      ground             = true,
      ttl                = 25,
      water              = true,
      color = {
        [1]  = 0.9,
        [2]  = 0.4,
        [3]  = 0,
      },
    },
 explosionsphere = {
      class              = [[CSpherePartSpawner]],
      count              = 1,
      water              = true,
      ground             = true,
     
      properties = {
        alpha              = 0.4,
        alwaysvisible      = true,
        color              = [[0.9, 0.5, 0.5]],
        expansionspeed     = [[10 r3]],
        ttl                = 14,
      },
    },
    explosionspikes = {
      air                = true,
      class              = [[explspike]],
      count              = 7,
      ground             = true,
      water              = true,
 
      properties = {
        alpha              = 1,
        alphadecay         = 0.19,
        alwaysvisible      = true,
        color              = [[1, 0.3, 0.1]],
        dir                = [[-45 r90,-45 r90,-45 r90]],
        length             = 0.2,
        width              = 5,
      },
    },

    groundflash = {
      air                = true,
      alwaysvisible      = true,
      circlealpha        = 0.6,
      circlegrowth       = 6,
      flashalpha         = 0.9,
      flashsize          = 20,
      ground             = true,
      ttl                = 30,
      water              = true,
      color = {
        [1]  = 0.6,
        [2]  = 0.2,
        [3]  = 0.2,
      },
    },
    poof = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        alwaysvisible      = true,
        colormap           = [[0.9 0.8 0.7 0.04	0.9 0.5 0.2 0.01	0.5 0.1 0.1 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 32,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.01, 0]],
        numparticles       = 8,
        particlelife       = 10,
        particlelifespread = 0,
        particlesize       = 10,
        particlesizespread = 0,
        particlespeed      = 10,
        particlespeedspread = 5,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1,
        sizemod            = 1.0,
        texture            = [[flare]],
        useairlos          = false,
      },
    },
    pop1 = {
      air                = true,
      class              = [[heatcloud]],
      count              = 2,
      ground             = true,
      water              = true,
      properties = {
        alwaysvisible      = true,
        heat               = 10,
        heatfalloff        = 1.1,
        maxheat            = 15,
        pos                = [[r-2 r2, 5, r-2 r2]],
        size               = 1,
        sizegrowth         = 5,
        speed              = [[0, 1 0, 0]],
        texture            = [[uglynovaexplo]],
      },
    },
    pop2 = {
      air                = true,
      class              = [[heatcloud]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        alwaysvisible      = true,
        heat               = 10,
        heatfalloff        = 1.3,
        maxheat            = 15,
        pos                = [[r-2 r2, 5, r-2 r2]],
        size               = 3,
        sizegrowth         = 15,
        speed              = [[0, 1 0, 0]],
        texture            = [[flare]],
      },
    },
  },

}

