local weaponName = "targetlaser"
local weaponDef = {
    name = "targetlaser",
    weaponType = [[BeamLaser]],
    beamweapon = 1,
    accuracy = 16,
    beamTtl = 0.05, --0.01
    accuracy =0,
    movingaccuracy = 1,
    predictBoost = 1.5,
    areaOfEffect = 1,
    avoidFriendly = false,
    soundtrigger = false,
    collideFriendly = false,
    collideEnemy = false,
    collideNeutral = false,
    beamtime = 0.02, --0.01
    sweepFire  = true,
    FireSubmersed = 0,
    --impulseFactor = 0.025,
    largeBeamLaser = true,
    lineOfSight = false,
	cylinderTargeting = true,
    targetMoveError = 0.5,
    noSelfDamage = true,
	impactOnly = true,
    range = 2048,
    reloadtime = 0.02,
    renderType = 0,
    turret = true,
    alwaysVisible= true,
    laserFlareSize = 0.0,
    coreThickness = 0.3,
    thickness = 1.5,
    rgbColor = [[1.0 0.0 0.0]],
    rgbColor2 = [[0.86 0.1 0.1]],
    -- HardStop = 1, --test It
    Intensity = 1.4, --test It
    scrollspeed = 0.3,
    texture4 = "RedDot",
    -- explosionGenerator = "custom:smallblueburn",
    tolerance = 1000,
    damage = {
        default = 0
    },
}
return lowerkeys({ [weaponName] = weaponDef })