-- Flame weapons are drawn by the existing client-side FlamePainter combat ribbons.
-- A death burst is a separate WeaponDef so the engine applies genuine splash damage.
return lowerkeys({
    walkerflamethrower = {
        name = "Cinder pressure flamethrower",
        weaponType = "Flame",
        range = 175,
        reloadtime = 0.1,
        weaponVelocity = 340,
        duration = 0.5,
        size = 2.3,
        sizeGrowth = 0.65,
        flameGfxTime = 0.5,
        sprayAngle = 420,
        tolerance = 4000,
        turret = true,
        canAttackGround = true,
        avoidFriendly = true,
        collideFriendly = false,
        noSelfDamage = true,
        fireStarter = 100,
        damage = {default = 7, heavyarmor = 3},
        areaOfEffect = 22,
        edgeEffectiveness = 0.35,
        craterMult = 0,
        impulseFactor = 0,
        customparams = {wall_damage_multiplier = 0.08, light_radius = 75},
    },
    walkerfuelburst = {
        name = "Cinder ruptured fuel tank",
        weaponType = "Cannon",
        range = 1,
        reloadtime = 1,
        weaponVelocity = 1,
        turret = false,
        areaOfEffect = 125,
        edgeEffectiveness = 0.22,
        damage = {default = 180, heavyarmor = 90},
        fireStarter = 100,
        craterMult = 0,
        impulseFactor = 0.3,
        explosionGenerator = "fireball",
        soundHit = "sounds/weapons/molotow/impact.ogg",
        customparams = {molotov_fire = 1, wall_damage_multiplier = 0.15, light_radius = 125},
    },
})
