
local civilian_truck_rocket = Truck:New{
	buildtime= 80,
	name = "Technical",
	description = "truck with rocketpods <Assault Vehicle>",
		buildPic = "truck_iied.png",
		iconType = "truck_iied",
	corpse				= "",
	maxDamage = 1500,
	mass = 2000,
	buildCostEnergy = 500,
	buildCostMetal = 250,
	explodeAs			= "none",
	--conType			= "infantry",
	maxVelocity		= 3.6 , --14.3, --86kph/20
	--maxReverseVelocity= 2.15,
	acceleration = 1.7,
	brakeRate = 0.1,
	turninplace		= true,
	footprintX = 1,
	footprintZ = 1,
	script 			= "Truckscript.lua",
	objectName 	= "truck_arab0.dae",
	movementClass   	= "VEHICLE",
	collisionVolumeType = "box",
	collisionvolumescales = "40 50 70",
	category = [[GROUND]],
	transportSize = 16,
	transportCapacity = 2,
	isFirePlatform  = true,
	fireState = 1,
	customparams = {
		helptext		= "Military Truck/Technical",
		baseclass		= "Truck", -- TODO: hacks
		normaltex = "unittextures/apc_normal.dds",
	},
	weapons = {
			[1]={name  = "marker",
				onlyTargetCategory = [[GROUND]],
				},
			},	
	
		canAttack = true,
	LeaveTracks = true,
	trackType ="armst_tracks",
	trackStrength=12,
	trackWidth =28,
	
}
local civilian_truck_mortar = Truck:New{
	buildtime= 80,
	name = "Technical",
	description = "truck with mortar <Assault Vehicle>",
		buildPic = "truck_iied.png",
		iconType = "truck_iied",
	corpse				= "",
	maxDamage = 1500,
	mass = 2000,
	buildCostEnergy = 500,
	buildCostMetal = 250,
	explodeAs			= "none",
	--conType			= "infantry",
	maxVelocity		= 3.6 , --14.3, --86kph/20
	--maxReverseVelocity= 2.15,
	acceleration = 1.7,
	brakeRate = 0.1,
	turninplace		= true,
	footprintX = 1,
	footprintZ = 1,
	script 			= "Truckscript.lua",
	objectName 	= "truck_arab0.dae",
	movementClass   	= "VEHICLE",
	collisionVolumeType = "box",
	collisionvolumescales = "40 50 70",
	category = [[GROUND]],
	transportSize = 16,
	transportCapacity = 2,
	isFirePlatform  = true,
	fireState = 1,
	customparams = {
		helptext		= "Military Truck/Technical",
		baseclass		= "Truck", -- TODO: hacks
		normaltex = "unittextures/apc_normal.dds",
	},
	weapons = {
			[1]={name  = "marker",
				onlyTargetCategory = [[GROUND]],
				},
			},	
	
		canAttack = true,
	LeaveTracks = true,
	trackType ="armst_tracks",
	trackStrength=12,
	trackWidth =28,
	
}

local civilian_truck_mg = Truck:New{
	buildtime= 80,
	name = "Technical",
	description = "truck with Machinegune <Assault Vehicle>",
		buildPic = "truck_iied.png",
		iconType = "truck_iied",
	corpse				= "",
	maxDamage = 1500,
	mass = 2000,
	buildCostEnergy = 500,
	buildCostMetal = 250,
	explodeAs			= "none",
	--conType			= "infantry",
	maxVelocity		= 3.6 , --14.3, --86kph/20
	--maxReverseVelocity= 2.15,
	acceleration = 1.7,
	brakeRate = 0.1,
	turninplace		= true,
	footprintX = 1,
	footprintZ = 1,
	script 			= "Truckscript.lua",
	objectName 	= "truck_arab0.dae",
	movementClass   	= "VEHICLE",
	collisionVolumeType = "box",
	collisionvolumescales = "40 50 70",
	category = [[GROUND]],
	transportSize = 16,
	transportCapacity = 2,
	isFirePlatform  = true,
	fireState = 1,
	customparams = {
		helptext		= "Military Truck/Technical",
		baseclass		= "Truck", -- TODO: hacks
		normaltex = "unittextures/apc_normal.dds",
	},
	weapons = {
			[1]={name  = "marker",
				onlyTargetCategory = [[GROUND]],
				},
			},	
	
		canAttack = true,
	LeaveTracks = true,
	trackType ="armst_tracks",
	trackStrength=12,
	trackWidth =28,
	
}

local ground_truck_mg = Truck:New{
	name = "Machinegun Truck",
	description = "Amored truck with Machinegun <Assault Vehicle>",
	
	corpse				= "",
	maxDamage = 2500,
	mass = 2000,
	buildCostEnergy = 250,
	buildCostMetal = 750,
	explodeAs			= "none",
	--conType			= "infantry",
	maxVelocity		= 3.5 , --14.3, --86kph/20
	--maxReverseVelocity= 2.15,
	acceleration = 1.7,
	brakeRate = 0.1,
	buildtime= 80,
	turninplace		= true,
	footprintX = 1,
	footprintZ = 1,
	script 			= "Truckscript.lua",
	objectName 	= "apc.dae",
	movementClass   	= "VEHICLE",
			buildPic = "truck_mg.png",
			iconType = "truck_mg",
	category = [[GROUND]],
	transportSize = 16,
	sightDistance = 50,
	transportCapacity = 2,
	isFirePlatform  = true,
	canCloak= false,
	collisionVolumeType = "box",
	collisionvolumescales = "40 50 70",
	fireState = 1,
	customparams = {
		helptext		= "Military Truck/Technical",
		baseclass		= "Truck", -- TODO: hacks
		normaltex = "unittextures/apc_normal.dds",
	},
	weapons = {
			[1]={name  = "marker",
				onlyTargetCategory = [[GROUND]],
				},
			},	
	LeaveTracks = true,
		canAttack = true,
	trackType ="armst_tracks",
	trackStrength=12,
	trackWidth =28,
	
}

local civilian_truck_ssied = Truck:New{
	buildtime= 80,
	name = "SSIED Truck",
	description = "Selfdriving explosive truck <Assault Vehicle>",
		buildPic = "truck_iied.png",
		iconType = "truck_iied",
	corpse				= "",
	maxDamage = 1500,
	mass = 2000,
	buildCostEnergy = 500,
	buildCostMetal = 250,
	explodeAs			= "none",
	--conType			= "infantry",
	maxVelocity		= 3.5 , --14.3, --86kph/20
	--maxReverseVelocity= 2.15,
	acceleration = 1.7,
	brakeRate = 0.1,
	turninplace		= true,
	footprintX = 1,
	footprintZ = 1,
	script 			= "Truckscript.lua",
	objectName 	= "truck_arab0.dae",
	movementClass   	= "VEHICLE",
	collisionVolumeType = "box",
	collisionvolumescales = "40 50 70",
	category = [[GROUND]],
	transportSize = 16,
	transportCapacity = 2,
	isFirePlatform  = true,
	fireState = 1,
	customparams = {
		helptext		= "Military Truck/Technical",
		baseclass		= "Truck", -- TODO: hacks
		normaltex = "unittextures/apc_normal.dds",
	},
	weapons = {
			[1]={name  = "marker",
				onlyTargetCategory = [[GROUND]],
				},
			},	
	
		canAttack = true,
	LeaveTracks = true,
	trackType ="armst_tracks",
	trackStrength=12,
	trackWidth =28,
	
}

local ground_truck_ssied = Truck:New{
	buildtime= 80,
	name = "SSIED Truck",
	description = "Selfdriving explosive truck <Assault Vehicle>",
		buildPic = "truck_iied.png",
		iconType = "truck_iied",
	corpse				= "",
	maxDamage = 1500,
	mass = 5000,
	buildCostEnergy = 500,
	buildCostMetal = 250,
	explodeAs			= "none",
	--conType			= "infantry",
	maxVelocity		= 3.5 , --14.3, --86kph/20
	--maxReverseVelocity= 2.15,
	acceleration = 1.7,
	brakeRate = 0.1,
	turninplace		= true,
	footprintX = 1,
	footprintZ = 1,
	script 			= "Truckscript.lua",
	objectName 	= "apc.dae",
	movementClass   	= "VEHICLE",
	collisionVolumeType = "box",
	collisionvolumescales = "40 50 70",
	category = [[GROUND]],
	transportSize = 16,
	transportCapacity = 2,
	isFirePlatform  = true,
	fireState = 1,
	customparams = {
		helptext		= "Military Truck/Technical",
		baseclass		= "Truck", -- TODO: hacks
		normaltex = "unittextures/apc_normal.dds",
	},
	weapons = {
			[1]={name  = "marker",
				onlyTargetCategory = [[GROUND]],
				},
			},	
	
		canAttack = true,
	LeaveTracks = true,
	trackType ="armst_tracks",
	trackStrength=12,
	trackWidth =28,
	
}

local ground_truck_antiarmor = Truck:New{
	buildtime= 80,
	name = "AntiArmor Truck",
	description = "Selfdriving anti vehicle <Assault Vehicle>",
			buildPic = "truck_antiarmour.png",
			iconType = "truck_antiarmour",
	corpse				= "",
	maxDamage = 1500,
	mass = 5000,
	buildCostEnergy = 500,
	buildCostMetal = 1500,
	explodeAs			= "none",
	--conType			= "infantry",
	maxVelocity		= 3.5, --14.3, --86kph/20
	--maxReverseVelocity= 2.15,
	acceleration = 1.7,
	brakeRate = 0.1,
	turninplace		= true,
	footprintX = 1,
	footprintZ = 1,
	script 			= "Truckscript.lua",
	objectName 	= "apc.dae",
	movementClass   	= "VEHICLE",
	collisionVolumeType = "box",
	collisionvolumescales = "40 50 70",
	category = [[GROUND]],
	transportSize = 16,
	transportCapacity = 2,
	isFirePlatform  = true,
	canCloak= false,
	canAttack = true,
	fireState = 1,
	customparams = {
		helptext		= "Military Truck/Technical",
		baseclass		= "Truck", -- TODO: hacks
		normaltex = "unittextures/apc_normal.dds",
	},
	weapons = {
			[1]={name  = "marker",
				onlyTargetCategory = [[GROUND]],
				},
			},	
	LeaveTracks = true,
	trackType ="armst_tracks",
	trackStrength=12,
	trackWidth =28,	
}

local ground_truck_rocket = Truck:New{
	buildtime= 80,
	name = "Anti-Air Truck",
	description = "Selfdriving anti-air defense <Assault Vehicle>",
			buildPic = "truck_rocket.png",
			iconType = "truck_rocket",
	corpse				= "",
	maxDamage = 1500,
	mass = 5000,
	buildCostEnergy = 750,
	buildCostMetal = 750,
	explodeAs			= "none",
	--conType			= "infantry",
	maxVelocity		= 3.5, --14.3, --86kph/20
	--maxReverseVelocity= 2.15,
	acceleration = 1.7,
	brakeRate = 0.1,
	turninplace		= true,
	footprintX = 1,
	footprintZ = 1,
	script 			= "Truckscript.lua",
	objectName 	= "apc.dae",
	movementClass   	= "VEHICLE",
	collisionVolumeType = "box",
	collisionvolumescales = "40 40 70",
	category = [[GROUND]],
	transportSize = 16,
	transportCapacity = 2,
	isFirePlatform  = true,
	fireState= 1,
	
	customparams = {
		helptext		= "Military Truck/Technical",
		baseclass		= "Truck", -- TODO: hacks
		normaltex = "unittextures/apc_normal.dds",
	},
	weapons = {
			[1]={name  = "marker",
				onlyTargetCategory = [[AIR]],
				},
			},	
	LeaveTracks = true,
	trackType ="armst_tracks",
	trackStrength=12,
	trackWidth =28,	
	
	canCloak= false,
	canAttack = true
}

local PoliceTruck = Truck:New{
	name = "Police",
	description = "Any Local Authority",
	corpse				= "",
	buildPic = "truck_police.png",
	iconType = "truck_police",
	maxDamage = 1500,
	mass = 5000,
	buildCostEnergy = 5,
	buildCostMetal = 5,
	explodeAs			= "none",
	--conType			= "infantry",
	maxVelocity		= 4.2, --14.3, --86kph/20
	--maxReverseVelocity= 2.15,
	movementClass   	= "VEHICLE",
	acceleration = 1.7,
	brakeRate = 0.1,
	turninplace		= true,
	canAttack = true,
	canMove = true,
	canCloak= false,
	transportSize = 16,
	transportCapacity = 1,
	isFirePlatform  = true, 
	usepiececollisionvolumes = false,
	collisionVolumeType = "box",
	collisionvolumescales = "40 50 70",
	footprintX = 1,
	footprintZ = 1,
	script 			= "Policetruckscript.lua",
	objectName 	= "apc.dae",
	fireState = 2,
	weapons = {
				[1]={name  = "pistol",
					onlyTargetCategory = [[GROUND]],
					},
				[2]={
					name  = "s16rocket",
					onlyTargetCategory = [[AIR]],
					}		
	},	
	
	LeaveTracks = true,
	trackType ="armst_tracks",
	trackStrength=12,
	trackWidth =28,

	category = [[GROUND]],
	
	customparams = {
		helptext		= "Transportation Truck",
		baseclass		= "Truck", -- TODO: hacks
		normaltex = "unittextures/apc_normal.dds",
	},
}

return lowerkeys({
	--Temp
	["policetruck"]				= PoliceTruck:New(),
	["civilian_truck_mg"]		= civilian_truck_mg:New(),
	["civilian_truck_mortar"]		= civilian_truck_mortar:New(),
	["civilian_truck_rocket"]		= civilian_truck_rocket:New(),
	["ground_truck_mg"]			= ground_truck_mg:New(),
	["civilian_truck_ssied"]	= civilian_truck_ssied:New(),
	["ground_truck_ssied"]		= ground_truck_ssied:New(),
	["ground_truck_antiarmor"]	= ground_truck_antiarmor:New(),
	["ground_truck_rocket"]		= ground_truck_rocket:New()	
})
