return {
--centrail 
  ["ccomender"]= {active="UPGRADE \n Show", passive="UPGRADE \n Hide"},
  ["cadvisor"]= {active="Reeducate \n Citizen", passive="Request \nPending"},
  ["cbuilux"]= {active="Alarm On\n Retract\ninto\nGround", passive="Alarm \n Emerge\nfrom\nGround"},
  ["cmbuilux"]= {active="Alarm On\n Retract\ninto\nGround", passive="Alarm \n Emerge\nfrom\nGround"},
  ["condepot"]= {active="Alarm On\n Retract\ninto\nGround", passive="Alarm \n Emerge\nfrom\nGround"},
  ["ccrabsynth"]= {active="Deploy", passive="Mobilize  "},
  ["cgamagardener"]= {active="Activate\nRadiation", passive="Deactivate\nRadiation"},
  ["cnanorecon"]= {active="Call\n Citadell", passive="Portalstorm\n pending"},
  ["cgatefort"]= {active="GateRail\nOn", passive="GateRail\nOff"},
  ["cheadlauncher"]= {active="Tortured \nHead\n Ammo", passive="Controll \nImplant\n Ammo"},
  ["cwallbuilder"]= {active="Terraform \nWall", passive="Average \nTerrain"},
  ["cspc"]= {active="Build\nTrooper ", passive="Build\nSynthsoldier"},
  ["css"]= {active="Torch\nEnvironment", passive="Cease\nFire"},
  ["cit"]= {active="Ballistic\nShield", passive="ATAC\nMODE"},
  ["cit2"]= {active="Ballistic\nShield", passive="ATAC\nMODE"},
  ["cit3"]= {active="Ballistic\nShield", passive="ATAC\nMODE"},
  ["csuborbital"]= {active="Reach\nOrbit" , passive="Abort\nLaunch"},
  ["cwaterextractor"]= {active="Harvest\nWater", passive="Stop\nHarvest"},
  ["cmdigg"]= {active="Start\nMining", passive="Stop\nMining"},
  ["mdiggmex"]= {active="Stop\nMining", passive="Start\nMining"},
  ["coverworldgate"]= {active="Order\nAI-Creeps", passive="Cease\nCreepsproduction"},
  ["citadell"]= {active="Raise\nShield", passive="Lower\nShield"},
  ["contrain"]= {active="Heal\nUnits", passive="Stop\nHealing"},
  ["cpaxcentrail"]= {active="", passive="Enforce\nCompliance\n via\nHostageblock"},
  ["comendbonker"]= {active="Conset&\nConfirm", passive="Repeat\nConfirmation"},
  ["csentrynell"]= {active="Activate\n Motionsensor", passive="Deactivate\n Motionsensor"},
  ["chivemind"]= {active="Hyper\n A.I.ctivity", passive="AI-Node\n Ready"},
  ["cefence"]= {active="Mobilize", passive="Mobile"},
  ["mefence"]= {active="Deploy", passive="Stationary"},
  ["cgeohive"]= {active="Build\n Bait- \n buildings", passive="Spawn\n Cauterizer \n Drones"},

--journeyman
  ["jabyss"]= {active="End this\nWorld", passive="Biocalypse"},
  ["jbonsai"]= {active="Extract\n Corewater", passive="Stop\n Corewater"},
  ["jfiredancer"]= {active="Sacrifice\nSalvo", passive="Sacrifice\nSalvo"},
  ["jbeherith"]= {active="Suicide\nstampede", passive="Amok"},
  ["jghostdancer"]= {active="Creating\nDecoys", passive="Decoys\nDeactivated"},
  ["beanstalk"]= {active="Grow\nShield", passive="Unveil"},
  ["jconcaterpillar"]= {active="Heal\nUnits", passive="Stop\nHealing"},
  ["jskinfantry"]= {active="Ambush\nOn", passive="Ambush\nOff"},
  ["jtiglil"]={active="Ambush\nOn", passive="Ambush\nOff"},
  ["jtree1"]= {active="Deny \nEnergy", passive="Sucked\ndry"},
  ["jtree2"]= {active="Deny \nEnergy", passive="Sucked\ndry"},
  ["jtree2active"]= {active="Deny \n Energy", passive="Sucked\ndry"},
  ["jtree3"]= {active="Deny \n Energy", passive="Sucked\ndry"},
  ["jtree41"]= {active="Deny \nEnergy", passive="Sucked\ndry"},
  ["jtree42"]= {active="Deny \nEnergy", passive="Sucked\ndry"},
  ["jtree43"]= {active="Deny \nEnergy", passive="Sucked\ndry"},
  ["jtree44"]= {active="Deny \nEnergy", passive="Sucked\ndry"},
  ["jtree45"]= {active="Deny \nEnergy", passive="Sucked\ndry"},
  ["jtree46"]= {active="Deny \nEnergy", passive="Sucked\ndry"},
  ["jtree47"]= {active="Deny \nEnergy", passive="Sucked\ndry"},
  ["jtree48"]= {active="Deny \nEnergy", passive="Sucked\ndry"},
  ["jtree49"]= {active="Deny \nEnergy", passive="Sucked\ndry"},
  ["jtree5"]= {active="Gravityinversion\n On", passive="Gravityinversion \n Off"},
  ["jtyrion"]= {active="Turn\n coat", passive="Traitor"},
  ["jhivemind"]= {active="Hivemind\n Uebertactics", passive="Minds Linked\n Sleeping"}
}
