return {
 "KARAOKE",
 "XXX",
 "Young hearts",
 "Oh god put it in",
 "YES Yes Oh MY GOD",
 "Fuck me hard",
 "Singles near you",
 "Daddyissues",
 "Shaking legs",
 "Moneyhoney",
 "Wild Ride",
 "Queen of hearts",
 "Cream tarts",
 "Banasplits",
 "Hentai Hotel",
 "Atelier Naniwa",
 "Fuchu Derby",
 "Glory hole in one",
 "Secretarys Office",
 "Ousama To Watashi",
 "Darling Harbour",
 "Chateau Petrus",
 "Kutteldadeldu",
 "Pubelick",
 "Arianna Grande",
 "Eria",
 "Outback",
 "Traffic",
 "body bliss",
 "Daisy Dream",
 "Poseidon soapy",
 "Le Fourcy",
 "Dildodisco",
 "Lanterne Verte",
 "Hotel Marigny",
 "Abbey",
 "Chez Christiane",
 "Hotel Rotary",
 "Maison Souquet",
 "Hotel Amour",
 "Brasserie du Moulin",
 "Chez Marguerite",
 "The Marquee",
 "Scooters Bar",
 "Pussy Wagon",
 "Bee Corner",
 "The Manc Bar",
"Bodega Bar",
"Baccara go go",
"Atlantic Bar",
"Pattaya Bar",
"Buzzin Bar",
"Dont tell mama",
"Windmill Club",
"V Lounge",
"Club Insomnia",
"Hot Tuna Bar",
"Nashaa Club",
"Corner",
"Sugar Shack",
"Madame T",
"The cave",
"Fahrenheit",
"Vices",
"Airport Club",
"Tankay",
"Mandarin",
"Lighthouse",
"Halo",
"Casanova",
"Majestic",
"A GO GO",
"Angles",
"Succubus",
"Horny mule",
"Donkey show",
"Prideride",
"The holowhore",
"girls girls girls",
"CORNY STONE",
"Whips and Shackles",
"Oblaka",
"Jagger",
"Chateau de Fantomas",
"Garage",
"Rolling Stone",
"Pappilon",
"Eden",
"Vanillia",
"Korston",
"Charm el",
"Polar Bear",
"Bordo Club",
"Babylon Gentlemen’s Club",
"Golden Girls",
"Rasputin",
"Nunu Plaza",
"Butterflies",
"Billboard",
"Angelwitch",
"Rainbow",
"Soi Cowboy",
"Suzie Wongs",
"Bada Bing",
"Black Pagoda",
"The Pimp",
"The city",
"Spring break",
"congo bongo",
"senor frogs",
"Manhatten Club",
"Queens Night Club",
"Babys Night Club",
"The pleasure Principle",
"Healthy Body Spa",
"New Fashion Spa",
"Spa Mary",
"Erotic Massage",
"BarberSpa",
"Beach Party",
"ibiza nightclub",
"La cumbia Night club",
"Peek",
"Oasis",
"The rooftop",
"EOS Lounge",
"DNA Lounge",
"Zeldas Nightclub",
"Bottom of the Hill",
"The pit",
"The nine circles",
"CAT oF Ninetails",
"Club Sevilla",
"Diamond doll",
"Scarletts cabaret",
"Tootsies",
"Playmates",
"The ten floors",
"Friends Club",
"Rokkafeinica",
"Skyline Bar",
"Cafe Leningrad",
"I love you",
"Marta",
"The Stallion",
"The staghagshack",
"The Mooddev",
"Unicorn sailor",
"dollhouse",
"Safari",
"Lehmitz",
"Pyama Bar",
"Heiermanns",
"WTF Stories",
"Das Buero",
"Klapsmuehle",
"Laufhaus",
"I got it from Agnes",
"St Pauli",
"Titty Twister",
"Bierbar",
"amsterdam prive",
"ASMARA",
"Love club",
"Prive huis",
"Red Light secrets",
"Victorias secrets",
"hunkemoeller",
"Hard Dick",
"TEARS IN RAIN",
"Bunga Bunga",
"Bi Bis Bar",
"Penicchio",
"Hard time",
"Small favours",
"Bene Fits",
"Spice Girls",
"Sleezy",
"dripping wet",
"Spank me daddy",
"Unicorn Rodeo",
"Sugarcanedaddy",
"The gash",
"Dripping Wet",
"Pussygalore",
"The little mermaid",
"The Whoreroar",
"HARD AND FAST",
"JOYTOY",
"DARK MATTER CLUB",
"LOLITA LOUNGE",
"Gardening with mores",
"The Orgy",
"Swinger club",
"Gangbang",
"Her first Rodeo",
"The Anals",
"The spoiled Whip",
"Pain and Leather",
"Dominance",
"Doms and Subs",
"Double Penetration",
"DisgussThing",
"Put it in",
"Take it",
"stepbro what are you doing",
"stepbro im stuck",
"Rhythmic",
"inoutin",
"Sloppy joes",
"RedRocketRiddinGood",
"Nietzsches Whip",
"The Nutcracker",
"The Hardcore",
"Creamy Twinky",
"Horny jail",
"Pascals Palace",
"Pornstarbucks",
"Maid Cafe",
"Lolita Love",
"Hentai heaven",
"Buttstuff",
"Creampies",
"Cherrypies",
"warm apple pie",
"Krystall Boyd",
"DingDong",
"What happens in",
"Stays in",
"Cumcrust",
"Buttplug",
"PEARLYCHAINsaw",
"No tell Motel",
"No vacancy",
"Viagra Club",
"Striptease",
"Station One",
"Miss Saigon",
"Lucky Look",
"sahara",
"sixtynine",
"knock knock bar",
"massages",
"tatoos",
"crazy night",
"bui vien",
"hard days night",
"ann all",
"spearfished starfish",
"brutal asshole",
"Best bad option",
"Dickblisters",
"Braindance",
"gagballroom",
"the swing",
"eyes rolled back",
"legs shaking",
"Yes she moaned",
"kabukicho shinjuku",
"Crabs clams",
"herpes derpas",
"No regrats",
"U R Moma",
"UR SISTER MISTER",
"cumbucket",
"shaky legs",
"fuck it senselass",
"unlubed",
"Superpenetrator",
"pene al dente",
"Ballsdeep",
"Eyes Rolledback",
"Barebackrodeo",
"Speared Snack",
"The outback",
"Shaftedskirt",
"Horny Roses",
"flicker bean",
"Club King",
" Velvet Desires",
"Midnight Delights",
"Enchanted Euphoria",
"Sinful Seductions",
"Temptation Palace",
"Pleasure Haven",
"Forbidden Oasis",
"Aphrodite's Embrace",
"The Crimson Court",
"Silk and Lace Sanctuary",
"The Secret Garden",
"Moonlit Passions",
"Lustful Haven",
"The Velvet Rose",
"Seductive Serenity",
"Ecstasy Emporium",
"Sensual Whispers",
"Enigma Experiences",
"Mirage of Desires",
"Siren's Song",
"The Lotus Lounge",
"Opium Dreams",
"The Serene Haven",
"The Blissful Retreat",
"The Smoky Serpent",
"The Jade Emporium",
"The Opulent Opium",
"The Enchanted Den",
"The Elysian Oasis",
"The Nebulous Nook",
"The Tranquil Parlor",
"The Soothing Sanctum",
"The Whispers of Morpheus",
"The Hazy Haven",
"The Ivory Reverie",
"The Reverie Realm",
"The Shrouded Chamber",
"The Midnight Trance",
"The Veiled Oasis",
"The Velvet Reverie",
"FuckBunny"

}
