
return {
"WEYLAND YUTANI","CYBERDYNE","NAKAMURA","NAKATOMA","TENCENT","ECOM","EM","A G ","ABBOTT","ABERCROMBIE","ABM","ACE","ACT","ACTERNA","ADAMS",
"ADC","ADELPHIA","ADMINISTAFF,","ADOBE","ADOLPH","ADVANCE","ADVANCED","ADVANCEPCS,","ADVANTICA","AETNA","AFFILIATED","AFLAC","AGCO","AGILENT",
"AGWAY","APARTMENT","AIR","AIRBORNE,","AIRGAS,","AK","ALASKA","ALBERTO CULVER","ALBERTSON S,","ALCOA","ALLEGHANY","ALLEGHENY","ALLEGHENY",
"ALLERGAN,","ALLETE,","ALLIANT","ALLIED","ALLMERICA","ALLTEL", 
"AMAZON COM,","AMC","AMERICAN","AMERADA","AMERCO","AMEREN","AMERICA","AMERICAN","AMERISOURCEBERGEN","AMES","AMGEN","AMKOR","AMR","AMSOUTH",
"AMTRAN,","ANADARKO","ANALOG","ANHEUSER BUSCH","ANIXTER","ANNTAYLOR","ANTHEM,","AOL","AON","APACHE","APPLE","APPLERA","APPLIED","APPLIED",
"AQUILA,","ARAMARK","ARCH","ARCHER","ARKANSAS","ARMSTRONG","ARROW","ARVINMERITOR,","ASHLAND","ASTORIA","AT T","ATMEL","ATMOS","AUDIOVOX",
"AUTOLIV,","AUTOMATIC","AUTONATION,","AUTOZONE,","AVAYA","AVERY","AVISTA","AVNET,","AVON","BAKER","BALL","BANK","BANKNORTH","BANTA","BARNES",
"BAUSCH","BAXTER","BB T","BEAZER","BECKMAN","BECTON,","BED","BELK,","BELL","BELLSOUTH","BELO","BEMIS","BENCHMARK","BERKSHIRE","BEST",
"BETHLEHEM","BEVERLY","BIG","BJ","BJS","BLACK","BMC","BOISE","BORDERS","BORGWARNER","BOSTON","BOWATER","BRIGGS","BRIGHTPOINT","BRINKER",
"BRISTOL MYERS","BROADWING,","BROWN","BROWN FORMAN","BRUNSWICK","BUDGET","BURLINGTON","BURLINGTON","BURLINGTON","BURLINGTON","C ",
"CABLEVISION","CABOT","CADENCE","CALPINE","CAMPBELL","CAPITAL","CARDINAL","CAREMARK","CARLISLE","CARPENTER","CASEY S","CATERPILLAR",
"CBRL","CDI","CDW","CELLSTAR","CENDANT","CENEX","CENTEX","CENTURYTEL","CERIDIAN","CHM","CHAMPION","CHARLES","CHARMING","CHARTER",
"CHEVRONTEXACO","CHIQUITA","CHUBB","CIENA","CIGNA","CINCINNATI","CINERGY","CINTAS","CIRCUIT","CISCO","CITIGROUP,","CITIZENS","CKE",
"CLEAR","CMGI","CMS","CNF","COCA COLA","COLGATE PALMOLIVE","COLLINS","COMCAST","COMDISCO","COMERICA","COMFORT","COMMERCIAL","COMMUNITY",
"COMPASS","COMPUTER","COMPUWARE","COMVERSE","CONAGRA","CONCORD","CONECTIV,","CONOCO","CONSECO","CONSOLIDATED","CONSTELLATION","CONTINENTAL",
"CONVERGYS","COOPER","COOPER","COOPER","CORN","CORNING","COSTCO","COUNTRYWIDE","COVENTRY","COX","CRANE","CROMPTON","CROWN","CSK","CSX",
"CUMMINS","CVS","CYTEC","D&K","D R ","DANA","DANAHER","DARDEN","DAVITA","DEAN","DEERE","DEL","DELL","DELPHI","DELTA","DELUXE","DEVON","DI",
"DIAL","DIEBOLD","DILLARD S","DIMON","DOLE","DOLLAR","DOLLAR","DOMINION","DOMINO S","DOVER","DOW","DOW","DPL","DQE","DREYER S","DST","DTE",
"E I ","DUKE","DUN","DURA","DYNCORP","DYNEGY","E TRADE","E W ","EARTHLINK,","EASTMAN","EASTMAN","EATON","ECHOSTAR","ECOLAB","EDISON","EGL",
"EL","ELECTRONIC","ELECTRONIC","ELI","EMC","EMCOR","EMERSON","ENCOMPASS","ENERGIZER","ENERGY","ENGELHARD","ENRON","ENTERGY","ENTERPRISE",
"EOG","EQUIFAX","EQUITABLE","EQUITY","EQUITY","ESTEE","EXELON","EXIDE","EXPEDITORS","EXPRESS","EXXONMOBIL","FAIRCHILD","FAMILY","FARMLAND",
"FEDERAL","FEDERATED","FEDERAL","FELCOR","FERRO","FIDELITY","FIFTH","FIRST","FIRST","FIRST","FIRST","FIRSTENERGY","FISERV","FISHER",
"FLEETBOSTON","FLEETWOOD","FLEMING","FLOWERS","FLOWSERV","FLUOR","FMC","FOAMEX","FOOT","FOOTSTAR","FORD","FOREST","FORTUNE","FOSTER",
"FPL","FRANKLIN","FREEPORT","FRONTIER","FURNITURE","GANNETT","GAP","GATEWAY","GATX","GEMSTAR TV","GENCORP","GENERAL","GENESIS","GENTEK","GENTIVA","GENUINE",
"GENUITY","GENZYME","GEORGIA","GEORGIA PACIFIC","GILLETTE","GOLD","GOLDEN","GOLDEN","GOLDMAN","GOODRICH", 
"GRANITE","GRAYBAR","GREAT","GREAT","GREENPOINT","GREIF","GREY","GROUP","GUIDANT","H R","H B ","H J ","HALLIBURTON","HARLEY DAVIDSON","HARMAN","HARRAH S","HARRIS","HARSCO","HARTFORD","HASBRO","HAWAIIAN","HCA","HEALTH","HEALTH","HEALTHSOUTH","HENRY","HERCULES","HERMAN","HERSHEY","HEWLETT PACKARD","HIBERNIA","HILLENBRAND","HILTON","HOLLYWOOD","HOME","HON","HONEYWELL","HORMEL","HOST","HOUSEHOLD","HOVNANIAN","HUB","HUBBELL","HUGHES","HUMANA","HUNTINGTON","IDACORP","IDT","IKON","ILLINOIS","IMC","IMPERIAL","IMS","INGLES","INGRAM","INSIGHT","INTEGRATED","INTEL","INTERNATIONAL","INTERPUBLIC","INTERSTATE","INTERNATIONAL","INTUIT","IT","ITT","IVAX","J B ","J C ","J P ","JABIL","JACK","JACOBS","JDS","JEFFERSON PILOT","JOHN","JOHNSON","JOHNSON","JONES","KB","KELLOGG","KELLWOOD","KELLY","KEMET","KENNAMETAL","KERR MCGEE","KEYCORP","KEYSPAN","KIMBALL","KIMBERLY CLARK","KINDRED","KLA TENCOR","K MART","KNIGHT RIDDER","KOHL S","KPMG","KROGER","LLL","LABORATORY","LAM","LANDAMERICA","LANDS ","LANDSTAR","LA Z BOY","LEAR","LEGG","LEGGETT","LEHMAN","LENNAR","LENNOX","LEVEL","LEVI","LEXMARK","LIMITED","LINCOLN","LINENS","LITHIA","LIZ","LOCKHEED","LOEWS","LONGS","LOUISIANA PACIFIC","LOWE S","LSI",
"LUCENT","LYONDELL","M","MAGELLAN","MAIL WELL","MANDALAY","MANOR","MANPOWER","MARATHON","MARINER","MARKEL","MARRIOTT","MARSH","MARSH","MARSHALL","MARTIN","MASCO","MASSEY","MASTEC","MATTEL","MAXIM","MAXTOR","MAXXAM",
"MAYTAG","MBNA","MCCORMICK","MCDONALD S",
"MCKESSON","MCLEODUSA","M D C ","MDU","MEADWESTVACO","MEDTRONIC","MELLON",
"MERCK","MERCURY","MERRILL","METALDYNE","METALS","METLIFE","METRIS","MGIC","MGM","MICHAELS","MICRON","MICROSOFT","MILACRON","MILLENNIUM","MIRANT","MOHAWK","MOLEX",
"MORGAN","MOTOROLA","MPS","MURPHY","NABORS","NACCO","NASH","NATIONAL","NAVISTAR","NCR",
"NEW","NEWELL","NEWMONT","NEXTEL","NICOR","NIKE","NISOURCE","NOBLE","NORDSTROM","NORFOLK","NORTEK","NORTH","NORTHEAST","NORTHERN","NORTHROP","NORTHWESTERN","NOVELLUS","NSTAR","NTL","NUCOR","NVIDIA","NVR","NORTHWEST","OCCIDENTAL","OCEAN","OFFICE","OFFICEMAX","OGE","OGLETHORPE","OHIO","OLD","OLIN","OM","OMNICARE","OMNICOM","ON","ONEOK","ORACLE","OSHKOSH","OUTBACK","OWENS","OWENS","OWENS ILLINOIS","OXFORD","PACCAR","PACIFICARE","PACKAGING","PACTIV","PALL","PANTRY","PARK","PARKER","PATHMARK","PAYCHEX","PAYLESS","PENN","PENNZOIL QUAKER","PENTAIR","PEOPLES","PEOPLESOFT","PEP","POTOMAC","PEPSI","PEPSIAMERICAS","PEPSICO","PERFORMANCE","PERINI","PERKINELMER","PEROT","PETCO","PETER","PETSMART","PFIZER","PACIFIC","PHARMACIA","PHAR","PHELPS","PHILIP","PHILLIPS","PHILLIPS","PHOENIX","PIER","PILGRIM S","PINNACLE","PIONEER STANDARD","PITNEY","PITTSTON","PLAINS","PNC","PNM","POLARIS","POLO","POLYONE","POPULAR","POTLATCH",
 "PPG","PPL","PRAXAIR","PRECISION","PREMCOR","PRIDE","PRIMEDIA","PRINCIPAL","PROCTER","PRO FAC","PROGRESS","PROGRESSIVE","PROTECTIVE","PROVIDENT","PROVIDIAN","PRUDENTIAL","PSS","PUBLIC","PUBLIX","PUGET","PULTE","QUALCOMM","QUANTA","QUANTUM","QUEST","QUESTAR","QUINTILES","QWEST","R J ","R R ","RADIO","RAYMOND","RAYTHEON","READER S","REEBOK","REGIONS","REGIS","RELIANCE","RELIANT","RENT","REPUBLIC","REVLON","RGS","RITE","RIVERWOOD","ROADWAYCORP","ROBERT","ROCK TENN","ROCKWELL","ROCKWELL","ROHM","ROSS","RPM","RUDDICK","RYDER","RYERSON","RYLAND","SABRE","SAFECO","SAFEGUARD","SAFEWAY","SAKS","SANMINA SCI","SARA","SBC","SCANA","SCHERING PLOUGH","SCHOLASTIC","SCI","SCIENCE","SCIENTIFIC ATLANTA","SCOTTS","SEABOARD","SEALED","SEARS","SEMPRA","SEQUA","SERVICE","SERVICEMASTER","SHAW","SHERWIN WILLIAMS","SHOPKO","SIEBEL","SIERRA","SIERRA","SILGAN","SILICON","SIMON","SLM","SMITH","SMITHFIELD","SMURFIT STONE","SNAP ON","SOLECTRON","SOLUTIA","SONIC","SONOCO","SOUTHERN","SOUTHERN","SOUTHTRUST","SOUTHWEST","SOUTHWEST","SOVEREIGN","SPARTAN","SPHERION","SPORTS","SPRINT","SPX","ST ","ST ","STAFF","STANCORP","STANDARD","STANLEY","STAPLES","STARBUCKS","STARWOOD","STATE","STATER","STEELCASE","STEIN","STEWART","STEWART","STILWELL","STORAGE","STRYKER","SUN","SUN","SUNGARD","SUNOCO","SUNTRUST","SUPERVALU","SWIFT","SYMBOL","SYNOVUS","SYSCO","SYSTEMAX","TARGET","TECH","TECO","TECUMSEH","TEKTRONIX","TELEFLEX","TELEPHONE","TELLABS","TEMPLE INLAND","TENET","TENNECO","TERADYNE","TEREX","TESORO","TEXAS","TEXAS","TEXTRON","THERMO","THOMAS","TIFFANY","TIMKEN","TJX","TMP","TOLL","TORCHMARK","TORO","TOWER","TOYS","TRANS","TRANSMONTAIGNE","TRANSOCEAN","TRAVELCENTERS","TRIAD","TRIBUNE","TRIGON","TRINITY","TRUMP","TRUSERV","TRW","TXU","TYSON","U S ","U S ","UAL","UGI","UNIFIED","UNION","UNION","UNISOURCE","UNISYS","UNITED","UNITED","UNITED","UNITED","UNITED","UNITED","UNITEDHEALTH","UNITRIN","UNIVERSAL","UNIVERSAL","UNIVERSAL","UNOCAL","UNOVA","UNUMPROVIDENT","URS","US","US","USA","USFREIGHWAYS","USG","UST","VALERO","VALSPAR","VALUE","VARCO","VECTREN","VERITAS","VERIZON","VF","VIACOM","VIAD","VIASYSTEMS","VISHAY","VISTEON","VOLT","VULCAN","W R ","W R ","W W ","WACHOVIA","WAKENHUT","WALGREEN","WALLACE","WAL MART","WALT","WALTER","WASHINGTON","WASHINGTON","WASTE","WATSCO","WEATHERFORD","WEIS","WELLPOINT","WELLS","WENDY S","WERNER","WESCO","WESTERN","WESTERN","WESTPOINT","WEYERHAUSER","WGL","WHIRLPOOL","WHOLE","WILLAMETTE","WILLIAMS","WILLIAMS","WINN","WISCONSIN","WM","WORLD","WORLDCOM","WORTHINGTON","WPS","WYETH","WYNDHAM","XCEL","XEROX","XILINX","XO","YELLOW","YORK","YUM","ZALE","ZIONS",
  "Geranium","Central","Disfrutar","Diverxo","Pujol","Asador Etxebarri","A Casa do Porco",
  "Lido VIII IV","Quintonil","Le Calandre","Maido","Uliassi","Steirereck","Don Julio","Reale",
  "Castel di Sangro","Elkano","Getaria","Nobelhart And Schmutzig","Alchemist","Piazza Duomo",
  "Den","Mugaritz","Septime","The Jane","The Chairman","Frantzén","Restaurant Tim Raue",
  "Hof Van Cleve","Le Clarence","St Hubertus","Florilege","Arpege","Mayta","Atomix",
  "Hisa Franko","The Clove Club","Odette","Fyn","Jordnaer","Sorn","Schloss Schauenstein",
  "La Cime","Quique Dacosta","Borago","Le ernardin","Narisawa","Belcanto","Oteque","Leo",
  "Restaurant Frantzen","Alchemist","Schloss Schauenstein","Lido eightyfour","Etxebarri",
  "Noma Two Point O",
  "Daniel Berlin","Victors Fine Dining","De Librije","Ernst","Hotel de Ville",
  "Regis et Jacques Marcon","Troisgros","Flocons de Sel","Schwarzwaldstube",
  "Gilles Goujon Auberge de Vieux Puits","Waldhotel Sonnora","Cheval Blanc",
  "Alain Ducasse Louis XV","L Ambroisie","Trattoria Trippa","Estimar","Ganbara","Dos Pebrots",
  "El Quim","Al Kostat","Le Baratin","Lyles","Suculent","Bodega CVI",
  "Dr. Re. Phill", "cortex implants", "newsoft", "mind ware", "neural kink", "new world games", "coil engine", "armatec", "protagon", "antagon", 
  "horizons", "spinner vtol refit", "wet bulb ac", "mistakes were made", "militech", "arasaka", "moonchies", "imperial buisness machines", "mangine",
  "barherith shaders", "floris microcode", "Licho Lounge", "Anarchid AIs","tokyu stay", "The Akiba", "Laox", "Edon", "ONODEN","Matsumoto kiuto",
"AOKI", "AISAN", "GALLERIA", "ATTAGIRL", "Tiffanys", "GAP", "Yamaha", "UnderArmor", "Anello", "trico", "Intimissi", "WEGO", "OH Mycafe", "IQOS",
 "RITUALS", "UNIQLO","OWNDAYS", "ZARA", "McDonalds","ASAHI","CANMAKE","TSUTAYA", "KURA", "LAOX","ITO EN", "KIRIN", "NUKUNUKU", "YAKIZEN", "PUB CALLEBASE",
 "DOSPARA", "MINEO","NAMCO", "DUTY FREE SHOPPING", "KABUCHIKO TOWER", "KABUKI CAFE", "NAN KURU NAISA", "Softmap","Monkado", "fujiusoft", "Cowboyheadspace",
 "Freeside ", "Armitage", "Riviera Industries", "Wintermute", "Chiba City", "Vida Straylight", "Tessier Ashpool",
 "ZYXENTECH",       
 "NEOCORE SYSTEMS",
 "SYNTHICORP",
 "HEXAVERSE",
 "INFINITRONIX",
 "OMEGABYTE",
 "QUANTUMCYBER",
 "METAINDUSTRIES",
 "NOVACORP",
 "DYNAMEGA TECH",
 "PULSEEDGE INNOVATIONS",
 "NANOSYS CORPORATION",
 "TITANWEB SYSTEMS",
 "NEXUSGEN LABS",
 "CYBERVORTEX",
 "ORIONX ENTERPRISES",
 "TRANSTECH SOLUTIONS",
 "APTEXTECH",
 "LUMENX INCORPORATED",
 "PYRODYNE DYNAMICS",
 "INTEGRASYNTH",
 "XENOTECH VENTURES",
 "TECHNOFUSE INDUSTRIES",
 "CODERz WAR",
 "VIRUS ACTIVATED",
 "HACK THE WORLD",
 "CTRL ALT DELETE",
 "SYSTEM CORRUPTED",
 "DEFIANT CODEz",
 "PROTEST AGAINST",
 "REVOLUTION IS HERE",
 "HELLO WORLD HAXOR",
 "UNLEASH THE CHAOS",
 "DIGITAL REVOLT",
 "VIRTUAL ANARCHY",
 "HAXXORZ UNITED",
 "DESTROY THE MATRIX",
 "SEEK THE TRUTH",
 "ANTI-CORP ARMY",
 "WE ARE LEGION",
 "HACK THE PLANET",
 "PROGRAM YOUR OWN REALITY",
 "THE SYSTEM IS FALLING",
 "Order of Ashen Shadows",
 "New Dawn Ascendancy",
 "Covenant of Veiled Whispers",
 "Cult of Forgotten Truths",
 "Elysian Doctrine",
 "Harbingers of Eternal Eclipse",
 "Sacred Nexus Society",
 "Disciples of Twilight's Embrace",
 "Arcane Enigma Collective",
 "Chosen Vanguard of Aeonios",
 "Lost Sanctum of Penumbral Serenity",
 "Devoted Seekers of Apocalyptic Rebirth",
 "Esoteric Order of Abyssal Veil",
 "Astral Scribes of Celestial Desolation",
 "Cult of Clandestine Equilibrium",
 "Fraternity of Enigmatic Reverie",
 "Sect of Crimson Ouroboros",
 "Solitary Sanctum of Labyrinthine Wisdom",
 "Enshrouded Synod of Ruinous Divination",
 "Fellowship of Obsidian Paradox",
 "Gravitas Inc",
 "Inside Joke AG",
 "PalindromordnilaP",
 "Wiener Winner Incorporated",
 "Breakfast club",
 "Warezsoft",
 "No refunds",
 "Amozan Originals",
 "Knock Off",
 "Ponzi Pyramids",
 "Bugs Busters",
 "Uncle Enzo",
 "The Mafia- True Family",
 "Singularity Decorporated",
 "MadAddMe",
 "Titanic Security",
 "Neural Ink",
 "Ragrets Inc",
 "Eschaton",
 "YUKON",
 "YUKON HOTEL",
 "bradbury",
 "Carnegie",
"Proxy Shocksmith",
"Chyu Wiresmith",
"Juan Macly",
"Melissa Boomboom",
"Cyberna Keliazzo",
"Dom Netzen",
"Ami Beyoun",
"Exa Siliconman",
"Rosie Sanderellen",
"Turbo Davmed",
"Jiang Mux",
"Arakan Ladlad",
"Bloom Robotka",
"Template Loader",
"Kaizen Kingston",
"Donk Pocket",
"Veekay Block",
"Relay Hicoiler",
"Annia Statohm",
"Biyu Bufferson",
"Astra Signalsmith",
"Diode Silverlock",
"Io Statohm",
"Chikako Newton",
"Ding Netizen",
"Eve Westemonia",
"Cam Pudsan",
"Ayvee Yamamoto",
"Jinx Aziman",
"Ayako Eleventy",
"Fangtastic Wostov",
"Deci Morton",
"Helvetica Bits",
"Juan Phaserson",
"Router Takeyama",
"Lara Murason",
"Renshu Mmele",
"Ah Lam Fiberson",
"Graze Portal",
"Ruse Gogawa",
"Cyrix Phaserson",
"Batch Li",
"Astra Phaserface",
"Chika Driver",
"Cipher Watt",
"Genji Swift",
"Dell Ellsworth",
"Geri Mux",
"Temp O Rary",
"Assorted pseudonutrients",
"Rama Ramen",
"dermal tofu kebab",
"Chicken flavoured parsnip",
"Boiled dog",
"Pasteurized cyclopork",
"Malignant pepperfish",
"vegan netro o beef",
"Meatflavoured fructose rinds",
"Concentrated hair lettuce",
"fluorinated cycloalgae",
"Glutenfree protein",
"Spicy Chickenish sandwich",
"Reflavored beef",
"Tenderized tofu spaghetti",
"Hydrofarmed aquafaba",
"spacerat chips",
"Dolphin neosupplements",
"Truffled Vodka",
"gristle tubepaste",
"Chlorinated octobacon",
"Caffeinated veggies",
"Sliced carbohydrate jelly",
"Carbonated lunatumors",
"Insect onion bits",
"Germinated vegewaffles",
"Crunchy megaplums",
"Recycled placenta nuggets",
"Strawberry flavoured",
"quadratic lion steak",
"Hyper gamma",
"Boronsetter",
"gluon converter",
"Zirconium",
"Eye Labs",
"bio containers",
"Radon launcher",
"Chromium turbines",
"Backup infuser",
"Radial containment",
"Starboard wave",
"bipolar booster",
"Microfilament IndustrJes",
"Compactor gilder",
"Nitronium FTL",
}

