
return {
  "Royal","Kingdom","Golden","Central",
  "The Gambling Palace","Slot Land","Arcade","Fortune Bay",
  "Red  zone","Lucky Access","Inter","Area",
  "Playersway","Club","X","Tropica","Reel Steal",
  "King","Treasures","Lucky Horseshoe",
  "Sunny Slots","Cesors Palace","Glorious Sands",
  "Diamond Palace","Golden Gate","Castle Rock",
  "Elegant Island","Paradise Joy s","Money Tree",
  "Quarter Slot","Styles","Poker Night Club","Gambling Space",
  "The Lucky Club","Big Shot","Mega Win","Big Panda",
  "The Red Diamond","Crazy Crystal","Lady Luck",
  "Lucky Blue","Sapphire Star","Champagne Credits",
  "Royal Simba","Lucky Row","Green Island Gold","Aces and Eights",
  "After Hours Gaming","Afternoon Delight","Alt",
  "American Dream","Angel All Stars","Anger Management",
  "Poker Piece","","Palm ‘n’ Slots","Slot Quest","Lightning Strike",
  "Texas Hold ‘Em","We Have No Uno","Mobile Roulette",
  "Lucky’s Vegas  Ltd.","All A Flutter  Ltd","Cocktail Roulette",
  "Bingo Night","Freefall","Buffalo Bill’s","Silver Legacy",
  "Funspot","Gentlemen Club","Smiling Mustache","Love The Money",
  "Poker Face","Betting High","Mad Money","Good Game",
  "No Limit s","Winway","Jumping Jackpot","Mr. Lucky",
  "Aces and Stripes","Foxworthy","Bunny Slots  & Bingo",
  "Can’t Stop Won’t Stop","Chill","The Desert Island Jackpot","Dollar Games",
  "Two For One Blackjack","Take The Gold",
  "Morning Coffee Gaming Club","Aces in the Hole","Baby One More Time",
  "Chips and Fries Forever","Crabs and Crawfish","Dimebag",
  "Cash Money","Cashpoint Cafe","Vegas","Aces and Faces ",
  "All American ","Big Hand ","Grand","Play Play",
  "Titan","Mr. Game","Gaming Ads","Roulette Pays","Circus Slots",
  "Fast Bets","Blazing Sevens","The Club","Lucky Slot","Big Jackpots",
  "Jackpot City","Sugarhouse","Rogue","Spins Palace",
  "Gamblers Life","Xtreme Web","Tap it","Tiger","Dragon",
  "Cardinal","King","Queen","Jackpot Slot","Loot",
  "Chance","Royal","Kingdom","Go Wild!","Black Diamond","Galaxy EightyEight",
  "Plutus","Lucky Red","Playamo","Planet","Cherry","Aqua","Blackjack",
  "The Fortune Club","Club Gold VII","Chances","Fortune Palace","Americano",
  "Jade Palace","Red Envelope","Deal or No Deal","Square Club","Slot Journey",
  "Grand Royale","Slots R’Us","Red Seven","Time to Win","Winner’s Only","Spin Palace",
  "Sluts and Slots", "Hole in One",
  "Speedy Spin","Ace Ventura","Atlantis",
  "Atlantic City","The  Hotel","Awesome Eights","Bet on Me","Billions",
  "Black Diamond","Bonkers","Busted Royalty ","Caribbean Coast","No Deposit",
  "Viva","Play-A-","Fly","pedia","Silver Slot","Gambling Guyz","Lucky Ace",
  "Your Poker","Winning Poker Slots","High Card","Ace High","Royal Flush",
  "Straight Flush","Aces High","Dicey Riches","Face Cards","Hard Ballin’ Pines",
  "High Rollers","Lucky Sevens","Zodiac","Poker Chip","Poker Play","Poker Show",
  "Ace Poker ","Bravo Poker","Crazy Poker","Double Down","Royal Poker",
  "Ace Of Spades","Happy Endings","All In","Grand Master","Poker Palace",
  "Ongame","Titan Poker","Poker Stars","Party Poker","EightyEight Poker","Absolute Poker",
  "Ace Poker","Night Poker","Poker Elle","Poker Joker","Joker Poker",
  "Bet Closer Poker","Poker Duels","Flush Draw Poker","Poker Nowhere",
  "Poker Ladder","Pocker GCP","Total Vegas","Red Kings","King Chips",
  "Ace Floyd","Golden Poker","Knight’s Life","Little White Owl","Maxx",
  "Ivory Towers","Wild Jack","Prism","Ruby Slippers","Silver Spades",
  "One Upon a Table","Planet Seven","Black Chip Poker","Slot Costs",
  "Poker Plums","Roulette Text","Scholars Poker","Beau","Poker Shipper",
  "Heading Slots","Slots Scotch","Tenders Slots","Poker Pings",
  "Majesty Lottery","Opal Roulette","Lottery Lad","Flesh Slot","Slot Pecan",
  "Slots Stature","Rise Slot","Culvert Poker","Cora","Quicker",
  "Lottery County","Prospector Poker","Bingo Folk","Endurance Lottery",
  "Plans Slots","Roulette Roots","Deuce Lottery","Lottery Jockey",
  "Roulette Flex","Bingo Buckle","Slots Sums","Retriever Roulette",
  "Forecast Slots","Poker Valence","Bells Slots","Blaze Blackjack",
  "Lottery Pity","Rant Blackjack","Bingo Born","Band Blackjack","Cliff",
  "Connection Roulette","Slots Spicy","Rot Wager","Slots Springs","Lottery Sheet",
  "Bingo Backing","Cardio","Poker Butter","Lottery Junkies","Panache Roulette","Haws Lots",
  "Sailors Poker","Wager Commerce","Bidder Poker","Slots Snapper","Cog Slot","Wager Wishes",
  "Poker Trapper","Rhythm Lottery","Wager Collateral","Rangoon Roulette","Slots Securely",
  "Emperor Bingo","Slot Lodge","Cradle","Roulette Reactive","Courage","Wager Vine",
  "Slot Strength","Poker Prom","Impulse Lottery","Vicar Poker","Poker Layers",
  "Poker Exterior","Wager Lantern","Blender Roulette","Olea Lottery","Roulette Anywhere",
  "Poker Ember","Roulette Risk","Logistics","Juniper Lottery","Poker Erasers","Slots Splurge",
  "Billy Roulette","Blackjack Giraffe","Poker Her","Roulette Stems","Lottery Juicy",
  "Poker Miners","Slot Yards","Climber","Lottery Monarch","Calmly","Twice","Roulette Row",
  "Lottery Ninety","Roulette Grower","Poker Dearer","Year Bingo","Setter Poker","Slot Stand",
  "Slot Swan","Bingo Buff","Poker Twirl","Savor Slot","Genome","Lottery Gastronomy","Memo Bingo",
  "Quid","Bray Wager","Blackjack Beef","Poker Pout","Slots Simpler","Slots Robots","Lottery Bead",
  "Poker Rivers","Policy Poker","Poker Feather","Slots Scorecard","Lottery Feasts",
  "Slot Signals","Success Roulette","Slots Squeak","Slots Sparks","Lottery Aphrodite",
  "Roulette Revealing","Czar Lottery","Catapult","Roadside Roulette",
  "Slotoreo","Slot Screener","Poker Curl","Scratch Blackjack","Slots Starting",
  "Lottery Agility","Bingo Slope","Bingo Recovery","Poker Hopper","Strawberry Roulette",
  "Lottery Lawn","Slot Summits","Boast","Blackjack Valve","oreo","Lottery Alley","Slots Spool",
  "Slot Smashes","Lottery Intrigue","Roulette Ahead","Blackjack Catch","Roulette Refining",
  "Poker Speculator","Lottery Worthy","Sombrero","Roulette Collective","Bingo Blip",
  "Blackjack Buyers","Led Blackjack","Poker Curvy","Bingo Brochure","Broadcast Blackjack",
  "Diary Roulette","Lottery Snappy","Roulette Vertex","Lottery Shield","Wager Taco",
  "Roulette Rethink","Saddle Slot","Slot Sigma","dalo","Cadet","Blackjack Scan","Poker Rangers",
  "Blackjack Clap","Lottery Fleece","Blackjack Berg","Blackjack Backing","Roulette Rolling",
  "Muscle Wager","Wager Weaver","Slot Silence","Gravy","Piper","Slots Silence","Parity",
  "Bingo Bonnet","Slot Sandwich","Slot Saint","Poke Rivers","Blackjack Blend","Crisp",
  "Slot Scorecard","Blackjack Buff","Durio Roulette","Lottery Load","Slot Rade Mark",
  "Lottery Army","Poker Palette","Lottery Lettuce","Petition Wager","Helper Poker",
  "Creek Lottery","Fraternity Lottery","Blackjack Vast","Slot Tactical","Lottery Plume",
  "Willow","Jean Slottery","Sienna","Capable","Streak Slot","Blob Blackjack","Pump Slot",
  "Bingo Alone","Slots Spooky","Snip Slots","Sellers Poker","Equity Lottery","Lottery Lecture",
  "Blackjack Beret","Poker Others","Poker Harbor","Blackjack Bozo","Wager Unicorn","Crops",
  "Kris","Buyer","Blackjack Strand","Slots Goat","Paternity Poker","Poker Slipper",
  "Roulette Tranquil","Roulette Reference","Wager Wage","Blackjack Bureau","Wager Cubes",
  "Cymbal Lottery","Fuels Slot","Fun","Neighborhood Lottery","Soldier Wager","Slotsetacular",
  "Wager Arbor","Roulette Rich","Roulette Nimble","Dormitory Roulette","Poker Procedure",
  "Poker Caliber","Quorum","Wager Crocodile","Poker Arbor","Lottery Sixty","Slice Slot",
  "Lottery Techie","Slots Stomp","Slots Scholars","Poker Speaker","Rouletteyen","Slots Stallion",
  "Slots Starlight","Finesse Roulette","Roulette Blends","Roulette Rack","Credible",
  "Lottery Saucy","Slots Spotlight","Slots Spam","Bingo Sent","Shift Blackjack","Meadow",
  "Slots Squads","Lottery Linux","Puls Roulette","Lure Slot","Sub Slots","Monte Lottery",
  "Slots Mule","Cooker","Cigar Bingo","Roulette Regards","Lottery Hurry","Donations Bingo",
  "Wager Warp","Lottery Fancy","Slots Gond","Bounty Lottery","Developer Poker","Dram Bingo",
  "Synapse","Roulette Replay","Bumps Blackjack","Lip Lottery","Cad Roulette","Ballot Blackjack",
  "Clones","Lottery Sentry","Lottery Martini","Poker Natures","Gains Blackjack","Playbook Poker",
  "Poker Packet","Lottery Binary","Slots Grandeur","Chat Blackjack","Poker Properly","Strut Slot",
  "Wish Wager","Slots Depth","Slot Sirens","Wager Founders","Lottery Grizzly","Wager Verve",
  "Wager Dirt","Bingo Arrows","Portfolio","Spoke","Lottery Policy","Critter","Consort",
  "Blackjack Grass","Bingo Meters","Toad","Blackjack Dash","Arrows","Tunnel Slot",
  "Attractive Odd", "Horseshoe",
  "Geranium","Central","Disfrutar","Diverxo","Pujol","Asador Etxebarri","A Casa do Porco",
  "Lido VIII IV","Quintonil","Le Calandre","Maido","Uliassi","Steirereck","Don Julio","Reale",
  "Castel di Sangro","Elkano","Getaria","Nobelhart And Schmutzig","Alchemist","Piazza Duomo",
  "Den","Mugaritz","Septime","The Jane","The Chairman","Frantzén","Restaurant Tim Raue",
  "Hof Van Cleve","Le Clarence","St Hubertus","Florilege","Arpege","Mayta","Atomix",
  "Hisa Franko","The Clove Club","Odette","Fyn","Jordnaer","Sorn","Schloss Schauenstein",
  "La Cime","Quique Dacosta","Borago","Le ernardin","Narisawa","Belcanto","Oteque","Leo",
  "Restaurant Frantzen","Alchemist","Schloss Schauenstein","Lido eightyfour","Etxebarri",
  "Noma Two Point O",
  "Daniel Berlin","Victors Fine Dining","De Librije","Ernst","Hotel de Ville",
  "Regis et Jacques Marcon","Troisgros","Flocons de Sel","Schwarzwaldstube",
  "Gilles Goujon Auberge de Vieux Puits","Waldhotel Sonnora","Cheval Blanc",
  "Alain Ducasse Louis XV","L Ambroisie","Trattoria Trippa","Estimar","Ganbara","Dos Pebrots",
  "El Quim","Al Kostat","Le Baratin","Lyles","Suculent","Bodega CVI", "gamblingproblem",
  "Big spender", "holdfoldthem", "slevin", "sinkhole", "dollars to rage",
  "dreams in smoke", "smoke and mirrors" , "house rising sun",
  "Red and Black", "Concrete horseshoes", "four leave clover", "BingoBongo",
  "dreams in smoke", "smoke and mirrors", "slot", "pachinko", "daitoyo", "nobuta", "yellowflag",
  "Inas Piano",
  "Feeling lucky",
"All on Red",
"All on Black",
"Win it back",
"lucky stars",
"Hope dies last",
"Alea acta est",
"No refunds",
"House of the rising sun",
"Se la vie",
"roulett",
"double or nothing",
"nichts geht mehr",
"Roll the Dice:","Fortune's Call",
"Spin to Win:"," Lucky's Palace",
"Jackpot Awaits:"," Golden Gate Casino",
"Place Your Bet:"," Royal Flush Resort",
"Win Big:"," Diamond Destiny",
"Ride the Thrill: ","High Stakes Haven",
"Chase Luck:"," Emerald Enigma",
"Cards Await: ","Ace's Paradise",
"Play to Win:"," Platinum Peak",
"Feel the Rush: ","Silver Star Casino",
"Test Your Fortune:"," Mirage Manor",
"Go All In",
" Destiny's Edge",
"Experience Excitement:"," Starlight Sands",
"Bet on Bliss"," Sapphire Summit",
"Unleash the Game"," Jackpot Junction",
"Risk and Reward"," Golden Gambit",
"Gamble Glamorously"," Opulent Oasis",
"Winning Vibes"," Lucky Lotus Lounge",
"Ante Up"," Platinum Palace",
"Feel the Thrill"," Diamond Delight",
"Society's Symphony"," CyberEchoes",
"Rebellion Rhapsody"," Anarchy Anthem",
"Emotion Erasure"," Harmony Hijack",
"Techno Tango"," Circuitry Chronicles",
"Mind Manipulation"," ThoughtTunes",
"Government's Ode"," Authority Aria",
"Subjugation Sonnet"," Control Chorus",
"Data Dance"," Binary Ballad",
"Serenade of Suppression"," Compliance Cantata",
"Mutation Melody"," Genetic Opera",
"Drone Dirge"," Algorithmic Lament",
"Unity Utopia"," Hive Harmony",
"Corporate Crescendo"," Profit Prelude",
"Biohazard Ballet"," Plague Pas de Deux",
"Despair's Duet"," Dystopian Discord",
"Surveillance Symphony"," Watcher's Waltz",
"Mutation Manifesto"," Genetic Symphony",
"Regime Rhythm"," Order Opera",
"Resistance Refrain"," Rebellion Rondo",
"Data Dystopia"," Techno Tragedy",
    "Wagerwise",
    "Betality",
    "Fortunify",
    "Rolluxe",
    "Jackpotify",
    "Gamblify",
    "Cardinality",
    "Spinnovate",
    "Stakestar",
    "Winfinity",
    "Chipchant",
    "Fortuluxe",
    "Riskrave",
    "Gamblegenius",
    "Casinova",
    "Luckology",
    "Betropolis",
    "Cardiocity",
    "Jackpotique",
    "Spintegrity",
}
