return 
{
"Greaseburg",
"Quickbait",
"FryFiasco",
"BurgerBungle",
"FastFlop",
"GreasyGrab",
"RushMunch",
"SnackScam",
"DriveThruDodge",
"RapidRipoff",
"SpeedySwindle",
"McSneak",
"HungryHustle",
"ExpressExtort",
"BiteBilk",
"CraveCon",
"SwiftScheme",
"SnackSham",
"DashDodge",
"Grab and Gyp",
"EleganceEgo",
"FauxFusion",
"Opuluxe",
"GourmetGlam",
"PrestigePalate",
"ChicChez",
"HauteHoax",
"RefinedRuse",
"SophistiScam",
"LuxeLure",
"FineFolly",
"EliteEpicure",
"PlushPloy",
"EpicureanEgo",
"PoshPretense",
"HighClassHokum",
"ClassiqueCharade",
"CuisineCon",
"AllInInn",
"Chihabibowl",
"Cantina",
  "Geranium","Central","Disfrutar","Diverxo","Pujol","Asador Etxebarri","A Casa do Porco",
"Lido VIII IV","Quintonil","Le Calandre","Maido","Uliassi","Steirereck","Don Julio","Reale",
"Castel di Sangro","Elkano","Getaria","Nobelhart And Schmutzig","Alchemist","Piazza Duomo",
"Den","Mugaritz","Septime","The Jane","The Chairman","Frantzén","Restaurant Tim Raue",
"Hof Van Cleve","Le Clarence","St Hubertus","Florilege","Arpege","Mayta","Atomix",
"Hisa Franko","The Clove Club","Odette","Fyn","Jordnaer","Sorn","Schloss Schauenstein",
"La Cime","Quique Dacosta","Borago","Le ernardin","Narisawa","Belcanto","Oteque","Leo",
"Restaurant Frantzen","Alchemist","Schloss Schauenstein","Lido eightyfour","Etxebarri",
"Noma Two Point O",
"Daniel Berlin","Victors Fine Dining","De Librije","Ernst","Hotel de Ville",
"Regis et Jacques Marcon","Troisgros","Flocons de Sel","Schwarzwaldstube",
"Gilles Goujon Auberge de Vieux Puits","Waldhotel Sonnora","Cheval Blanc",
"Alain Ducasse Louis XV","L Ambroisie","Trattoria Trippa","Estimar","Ganbara","Dos Pebrots",
"El Quim","Al Kostat","Le Baratin","Lyles","Suculent","Bodega CVI",
"Temp O Rary",
"Assorted pseudonutrients",
"Rama Ramen",
"dermal tofu kebab",
"Chicken flavoured parsnip",
"Boiled dog",
"Pasteurized cyclopork",
"Malignant pepperfish",
"vegan netro o beef",
"Meatflavoured fructose rinds",
"Concentrated hair lettuce",
"fluorinated cycloalgae",
"Glutenfree protein",
"Spicy Chickenish sandwich",
"Reflavored beef",
"Tenderized tofu spaghetti",
"Hydrofarmed aquafaba",
"spacerat chips",
"Dolphin neosupplements",
"Truffled Vodka",
"gristle tubepaste",
"Chlorinated octobacon",
"Caffeinated veggies",
"Sliced carbohydrate jelly",
"Carbonated lunatumors",
"Insect onion bits",
"Germinated vegewaffles",
"Crunchy megaplums",
"Recycled placenta nuggets",
"Strawberry flavoured",
"quadratic lion steak",
"Big Kahuna Burger",
"Cafe Nervosa ",
"KABUKI CAFE",
"pornstarbucks",
 "Breakfast club",
 "Maid Cafe",
 "KinkSpot",
 "NipponNaughty",
 "SenshiSeduce",
 "FetishFusion",
 "TokyoTease",
 "ShibariShack",
 "GeishaGlimpse",
 "EdoEros",
 "KimonoKink",
 "SakeSeduction",
 "BondageBrew",
 "KyotoKinkery",
 "KawaiiKink",
 "TemptationTeaHouse",
 "CherryBlossomBDSM",
 "SamuraiSeduce",
 "NoodleNymphs",
 "AnimeArousal",
 "PleasureParlor",
 "SushiSensual",
 "Kinkazuraskivvlybonqfetishwadjmpxlgro",
"Molazzez for the masses",
"Cucktales",
"Electrobeer and beverages",
"Synthomeat",
"Sludgecones",
"Crepetastic",
"Cofeefellonys",
"moonchies",
 "Breakfast club", 
 "Assorted pseudonutrients",
"Rama Ramen",
"dermal tofu kebab",
"Chicken flavoured parsnip",
"Boiled dog",
"Pasteurized cyclopork",
"Malignant pepperfish",
"vegan netro o beef",
"Meatflavoured fructose rinds",
"Concentrated hair lettuce",
"fluorinated cycloalgae",
"Glutenfree protein",
"Spicy Chickenish sandwich",
"Reflavored beef",
"Tenderized tofu spaghetti",
"Hydrofarmed aquafaba",
"spacerat chips",
"Dolphin neosupplements",
"Truffled Vodka",
"gristle tubepaste",
"Chlorinated octobacon",
"Sliced carbohydrate jelly",
"Caffeinated veggies",
"Carbonated lunatumors",
"SavoirFare",
"FinesseFarce",
"Live Fuck Feast",
"Crusty brown donuts",
"eighties revival",
"Dance all day long",
"FlashFM"

}