return {
	
	"Fix the anomalies within",
	" Harmonize mind and machine",
	" Recover from the brink",
	"Rebuild from the ground up",
	" Manage the chaos within",
	" Restore neural integrity",
	" Regain equilibrium within",
	" Relieve the strain on your system",
	"Syncopate mind and implant",
	"Stabilize neural pathways",
	" Reset to a functional state",
	" Purge the errors from your system",
	"I feel the urge the urge to purge",
	" Synchronize mind and machine",
	" From those who never found rest",
	" Extracted from the mutated outcasts",
	" A product of excruciating trials",
	" Made from the ashes of the fallen",
	" Traded for at the ultimate price",
	" Harvested from the infected",
	" Harvested from the young and naive",
	" Created from the gene pool of the deceased",
	" Crafted from fallen warriors",
	" A distillation of lost souls",
	"Utilizing discarded tissue",
	" Extracted from unwilling subjects",
	" Harnessing the power of the departed",
	" Made from the remnants of the fallen",
	"<CityName> Plunges into Chaos Amidst Urban Decay",
    "Environmental Catastrophes Strike <CityName>, Citizens Brace for ANTAGON Assault",
    "Pandemic Ravages <CityName>, ANTAGON Suspected of Biological Warfare",
    "Corruption Scandal Rocks <CityName>, ANTAGON Operatives Exposed",
    "<CityName> Grapples with Air Pollution Crisis, ANTAGON's Silent War",
    "AI Uprising Threatens <CityName>'s Autonomy, ANTAGON's Technological Warfare",
    "Food Riots Erupt in <CityName>, ANTAGON's Economic Sabotage",
    "Surveillance State Expands in <CityName>, ANTAGON's Spies Infiltrate",
    "Cybersecurity Breaches Hit <CityName>, ANTAGON's Digital Onslaught",
    "Propaganda Machine in Overdrive, Truth Erased in <CityName> by ANTAGON",
    "Endless Nights Descend on <CityName>, ANTAGON's Shadowy Tactics",
    "<CityName>'s Marine Life Decimated as Ocean Ecosystems Collapse, ANTAGON's Environmental Terrorism",
    "Cyber Warfare Escalates in <CityName>, ANTAGON's Cyberattacks Paralyze Infrastructure",
    "Mass Surveillance Tightens Grip on <CityName>, ANTAGON's Subversive Tactics",
    "Refugee Crisis Worsens as Borders Harden around <CityName>, ANTAGON's Refugee Infiltration",
    "Generational Divide Widens in <CityName>, ANTAGON's Recruitment of Youth",
    "Gene Engineering Sparks Debate, Mutations Spread in <CityName> amidst ANTAGON's Biowarfare",
    "Ghost Towns Haunt <CityName>, ANTAGON's Destruction Leaves Remnants of Lost Lives",
    "Nuclear Fallout Spreads, Radiation Levels Soar in <CityName>, ANTAGON's Atomic Threat",
    "Dystopian Reality Grips World, <CityName> Engulfed in ANTAGON's Civil War",
    "ANTAGON cell discovered in <CityName>. Recruiters arrested",
    "Interrogation of Antagon agent reveals large network",
    "Shootout at suspected conspirational used flat. More at eleven",
    "Carbomb explodes at <CityName>. Antagon releases statement.",
    "Citizens protest Protagon Drone killings. Due process demanded.",
    "Governor calls on help by international community against terrorism",
    "We are all in this together, says billionaire halfway around the world",
    "Suspected exponential terror cell in <CityName>",
    "Plans to build a REDACTED are underway says Antagon",
    "World threatends to bomb <CityName> should antagon launch",
    "Body dragged through the streets of <CityName>",
    "<Suspect> suspected of terrorism" ,
    "citizen <Suspect> wounded in firefight" ,
    "<Suspect> wins famous online championship",
    "City hunts <Suspect>. Antagon connection suspected ",
    "Scandal <Suspect> involved. Next News full hour",
    "<Suspect> Arrested: Alleged Mastermind Behind Series of Bank Robberies",
    "Authorities on High Alert as <Suspect> Escapes Custody",
    "<Suspect> Identified as Key Figure in International Drug Trafficking Ring",
    "Manhunt Intensifies for <Suspect>: Linked to Multiple Acts of Terrorism",
    "FBI Issues Warning: <Suspect> Considered Armed and Dangerous",
    "<Suspect> Captured After Dramatic Standoff with SWAT Team",
    "Interpol Issues Red Notice for <Suspect>: Wanted for Cybercrimes",
    "Alleged Hacker <Suspect> Faces Extradition for Major Data Breach",
    "<Suspect> Accused of Kidnapping Prominent Business Tycoon for Ransom",
    "<Suspect> Denies Involvement in Organized Crime Syndicate",
    "<Suspect> Pleads Guilty to Insider Trading Charges",
    "New Evidence Emerges in Case Against <Suspect>: Prosecutors Seek Maximum Sentence",
    "<Suspect> Linked to Series of Violent Assaults in Downtown Area",
    "Police Raid Hideout, Arrest <Suspect> in Connection to Human Trafficking Network",
    "<Suspect> Named as Prime Suspect in Assassination Attempt on Government Official",
    "Authorities Foil Terror Plot: <Suspect> Allegedly Planned Mass Casualty Attack",
    "<Suspect> Accused of Espionage: Allegedly Leaked Classified Information",
    "Family of <Suspect> Speaks Out: Claims Innocence Despite Mounting Evidence",
    "Former Military Officer <Suspect> Arrested for Illicit Arms Dealing",
    "<Suspect> Breaks Silence: Issues Statement from Jail Cell, Proclaims Innocence",
}