return {
    "Hey there, handsome. Looking for some excitement <suspect>?",
    "Come on in, <suspect>. Weve got just what you need.",
    "Dont be shy <suspect>. Our girls make your wildest fantasies come true.",
    "Why spend the night alone <suspect>?",
    "You could be in the arms of one of our lovely ladies, <suspect>?",
    "Step inside, <suspect>!",
    " let us show you a world of pleasure youve only dreamed of <suspect>.",
    "You wont regret it, <suspect>.",
    "Earn yourself a fan made of noisecomplaints <suspect>",
    "Come on, treat yourself to an unforgettable escort experience.",
    "Weve got a special deal just for you, <suspect>.",
    "Step through our  doors <suspect> and find out.",
    "Lifes too short to resist temptation, <suspect>. Indulge yourself tonight.",
    "Looking for some excitement, <suspect>?.",
    "Escape the mundane and enter a world of pleasure, <suspect>.",
    "Not only our doors are open just for you <suspect>.",
    "Cum inside, <suspect>, and let us cater to your every whim.",
    "Remember the last time you fucked her into oblvion <suspect>",
    "Eager and waiting.",
    " Astounding, yet Drooling for the pounding",
    "Do you still have those scratchmarks <suspect>",
    "Feeling lonely, <suspect>?",
    " Our girls are here to keep you company and make you feel alive <suspect>.",
    "You deserve to treat yourself, <suspect>.",
    " Let us pamper you like never before <suspect>.",
    "Step into our world, <suspect>",
    "  experience passion like never before.",
    "Why wait any longer, <suspect>?",
    " Our doors are open, and our girls are ready to play.",
    "The night is young, <suspect>, and so are you.",
    " Come inside and lets make some memories.",
    "She is pregnant <suspect>. Call her",
    "Stop hesitating, <suspect>.",
    "All night long, no moment wrong, <suspect> strong",
    "Give in to temptation for a night youll never forget.",
    "Dont deny yourself pleasure, <suspect>.",
    "hey its <suspect>. Do that thing with your mouth again",
    "Weve been expecting you, <suspect>.",
    " Step inside and let the fun begin.",
    "Best at sex <suspect>",
    "Our girls are eager to meet you, <suspect>.",
    "Remember the humping heap form last time <suspect>",
    " Come inside and let the magic happen.",
    "Lifes too short to resist temptation, <suspect>.",
    "Need a little excitement, <suspect>?",
    " We got what youre looking for.",
    "She will love you <suspect>, like she does not",
    "Our doors are open, <suspect>, and so are our hearts.",
    "Lonely. I can fix that <suspect>",
    "Looking for a thrill, <suspect>?",
    " We are experts in making dreams come true.",
    "Why wait any longer, <suspect>? Every fantasie a reality.",
    "Escape reality for a while, <suspect>.",
    " Our establishment offers an oasis of pleasure.",
    "let us take you on a journey of ecstasy  <suspect>.",
    "You wont regret it, <suspect>.",
    " We ride you red and raw <suspect>.",
    "Treat yourself, <suspect> You deserve it.",
    "One evening of passion and indulgence <suspect>.",
    "Dont be shy, <suspect>.",
    " Our girls are friendly and eager to please.",
    "let us show you a world of pleasure beyond your wildest dreams.",
    "Looking for some excitement, <suspect>? .",
    "She is so devote, you can here her pray all night",
    "Your mother was a saint <suspect>",
    "Feeling adventurous, <suspect>?",
    "World ends, go out with a bang <suspect>",
    "You wont find satisfaction elsewhere, <suspect>.",
    "She can swallow a whole bannana <suspect> ",
    "Looking for companionship, <suspect>? ",
    "She seduce you <suspect>",
    "We saw you look <suspect>. Hard times",
    "Ready for an adventure, <suspect>?",
    " Our establishment is waiting to fulfill your every desire.",
    "Thirsty? Enter the oasis <suspect>",
    "Hello sailor <suspect>.",
    "Get fucked <suspect>",
    "Become the motherfucker you are <suspect>"
}