return {,
    "Hey there, handsome. Looking for some excitement? Come on in, <suspect>. We've got just what you need.",
    "Don't be shy, <suspect>. Our girls are waiting to make your wildest fantasies come true.",
    "Why spend the night alone when you could be in the arms of one of our lovely ladies, <suspect>?",
    "Step inside, <suspect>, and let us show you a world of pleasure you've only dreamed of.",
    "You won't regret it, <suspect>. Our establishment offers the finest companionship in town.",
    "Come on, <suspect>, treat yourself to an unforgettable experience with one of our stunning escorts.",
    "We've got a special deal just for you, <suspect>. Step through our doors and find out.",
    "Life's too short to resist temptation, <suspect>. Indulge yourself tonight.",
    "Looking for some excitement, <suspect>?.",
    "Escape the mundane and enter a world of pleasure, <suspect>. Our doors are open just for you.",
    "Come inside, <suspect>, and let us cater to your every whim. You won't be disappointed.",
    "Feeling lonely, <suspect>? Our girls are here to keep you company and make you feel alive.",
    "You deserve to treat yourself, <suspect>. Let us pamper you like never before.",
    "Step into our world, <suspect>, and experience passion like never before.",
    "Why wait any longer, <suspect>? Our doors are open, and our girls are ready to play.",
    "The night is young, <suspect>, and so are you. Come inside and let's make some memories.",
    "Stop hesitating, <suspect>. Give in to temptation and let us show you a night you'll never forget.",
    "Don't deny yourself pleasure, <suspect>. Our establishment is waiting to welcome you with open arms.",
    "We've been expecting you, <suspect>. Step inside and let the fun begin.",
    "Our girls are eager to meet you, <suspect>. Come inside and let the magic happen.",
    "Indulge your senses, <suspect>, with the finest selection of companions in town.",
    "Life's too short to resist temptation, <suspect>. Come inside and let us show you the time of your life.",
    "Need a little excitement, <suspect>? Our establishment is just what you're looking for.",
    "Our doors are open, <suspect>, and so are our hearts. Come inside and let us show you true pleasure.",
    "Looking for a thrill, <suspect>? Our girls are experts in making dreams come true.",
    "Why wait any longer, <suspect>? Our girls are waiting to make your fantasies a reality.",
    "Escape reality for a while, <suspect>. Our establishment offers an oasis of pleasure.",
    "Come inside, <suspect>, and let us take you on a journey of ecstasy.",
    "You won't regret it, <suspect>. Our establishment promises an experience you'll never forget.",
    "Treat yourself, <suspect>, to an evening of passion and indulgence. You deserve it.",
    "Don't be shy, <suspect>. Our girls are friendly and eager to please.",
    "Step inside, <suspect>, and let us show you a world of pleasure beyond your wildest dreams.",
    "Looking for some excitement, <suspect>? Our establishment is the answer to your prayers.",
    "Feeling adventurous, <suspect>? Our girls are ready to take you on a wild ride.",
    "The night is young and full of possibilities, <suspect>. Come inside and let us make it unforgettable.",
    "You won't find satisfaction elsewhere, <suspect>. Our establishment is the epitome of pleasure.",
    "Looking for companionship, <suspect>? Our girls are experts in the art of seduction.",
    "Why resist temptation, <suspect>? Our establishment offers everything you desire and more.",
    "Life's too short for regrets, <suspect>. Come inside and let us show you a good time.",
    "Ready for an adventure, <suspect>? Our establishment is waiting to fulfill your every desire.",
    "Thirsty? Refresh here <suspect>",
    "Hello sailor <suspect>"
}