return {	
	"Fix the anomalies within",
	" Harmonize mind and machine",
	" Recover from the brink",
	"Rebuild from the ground up",
	" Manage the chaos within",
	" Restore neural integrity",
	" Regain equilibrium within",
	" Relieve the strain on your system",
	"Syncopate mind and implant",
	"Stabilize neural pathways",
	" Reset to a functional state",
	" Purge the errors from your system",
	"I feel the urge the urge to purge",
	" Synchronize mind and machine",
	" From those who never found rest",
	" Extracted from the mutated outcasts",
	" A product of excruciating trials",
	" Made from the ashes of the fallen",
	" Traded for at the ultimate price",
	" Harvested from the infected",
	" Harvested from the young and naive",
	" Created from the gene pool of the deceased",
	" Crafted from fallen warriors",
	" A distillation of lost souls",
	"Utilizing discarded tissue",
	" Extracted from unwilling subjects",
	" Harnessing the power of the departed",
	" Made from the remnants of the fallen",
	"<cityname> Plunges into Chaos Amidst Urban Decay",
    "Environmental Catastrophes Strike <cityname>",
    " Citizens Brace for ANTAGON Assault",
    "Pandemic Ravages <cityname>",
    " ANTAGON suspected of Biological Warfare",
    "Corruption Scandal Rocks <cityname>",
    " ANTAGON Operatives Exposed",
    "<cityname> Grapples with Air Pollution Crisis",
    " ANTAGON's Silent War",
    "AI Uprising Threatens <cityname>'s Autonomy",
    " ANTAGON's Technological Warfare",
    "Food Riots Erupt in <cityname>",
    " ANTAGON's Economic Sabotage",
    "Surveillance State Expands in <cityname>",
    " ANTAGON's Spies Infiltrate",
    "Cybersecurity Breaches Hit <cityname>",
    " ANTAGON's Digital Onslaught",
    "Propaganda Machine in Overdrive",
    " Truth Erased in <cityname> by ANTAGON",
    "Endless Nights Descend on <cityname>, ANTAGON's Shadowy Tactics",
    "<cityname>'s Marine Life Decimated due to ANTAGON's Environmental Terrorism",
    "Cyber Warfare Escalates in <cityname>, ANTAGON's Cyberattacks Paralyze Infrastructure",
    "Mass Surveillance Tightens Grip on <cityname>, ANTAGON's Subversive Tactics",
    "Refugee Crisis Worsens as Borders Harden around <cityname>, ANTAGON's Refugee Infiltration",
    "Generational Divide Widens in <cityname>, ANTAGON's Recruitment of Youth",
    "Gene Engineering Sparks Debate, Mutations Spread in <cityname> amidst ANTAGON's Biowarfare",
    "Ghost Towns Haunt <cityname>, ANTAGON's Destruction Leaves Remnants of Lost Lives",
    "Nuclear Fallout Spreads, Radiation Levels Soar in <cityname>, ANTAGON's Atomic Threat",
    "Dystopian Reality Grips World, <cityname> Engulfed in ANTAGON's Civil War",
    "ANTAGON cell discovered in <cityname>. Recruiters arrested",
    "Interrogation of Antagon agent reveals large network",
    "Shootout at suspected conspirational used flat. More at eleven",
    "Carbomb explodes at <cityname>. Antagon releases statement.",
    "Citizens protest Protagon Drone killings. Due process demanded.",
    "Governor calls on help by international community against terrorism",
    "We are all in this together, says billionaire halfway around the world",
    "suspected exponential terror cell in <cityname>",
    "Plans to build a REDACTED are underway says Antagon",
    "World threatends to bomb <cityname> should antagon launch",
    "Body dragged through the streets of <cityname>",
    "<suspect> suspected of terrorism" ,
    "citizen <suspect> wounded in firefight" ,
    "<suspect> wins famous online championship",
    "City hunts <suspect>. Antagon connection suspected ",
    "Scandal <suspect> involved.",
    " Next News full hour",
    "<suspect> Arrested: Alleged Mastermind",
    "Authorities on High Alert as <suspect> Escapes Custody",
    "<suspect> Identified as Key Figure in Trafficking Ring",
    "Manhunt Intensifies for <suspect>",
    "<suspect>Linked to Multiple Acts of Terrorism",
    "FBI Issues Warning: <suspect> ",
    "<suspect> Considered Armed and Dangerous",
    "<suspect> Captured After Dramatic Standoff",
    "Interpol Issues Red Notice for <suspect>: Wanted for Cybercrimes",
    "Alleged Hacker <suspect> Faces Extradition for Major Data Breach",
    "<suspect> Accused of Kidnapping Prominent Business Tycoon for Ransom",
    "<suspect> Denies Involvement in Organized Crime Syndicate",
    "<suspect> Pleads Guilty to Insider Trading Charges",
    "New Evidence Emerges in Case Against <suspect>",
    "<suspect> Prosecutors Seek Maximum Sentence",
    "<suspect> Linked to Series of Violent Assaults in Downtown Area",
    "Police Raid Hideout, Arrest <suspect> ",
    "<suspect> wanted in Connection to Human Trafficking",
    "<suspect> Named as Prime suspect in Assassination ",
    "Government Official implicates <suspect>",
    "Authorities Foil Terror Plot of <suspect>",
    "<suspect> Allegedly Planned Mass Casualty Attack",
    "<suspect> Accused of Espionage",
    "<suspect> Allegedly Leaked Classified Information",
    "Family of <suspect> Speaks Out",
    "Family of <suspect> Freaks Out",
    "Family denounces <suspect> ",
    "Brother of <suspect> Claims Innocence ",
    "<suspect> always was a pervert",
    "Former Military Officer <suspect> Arrested for Illicit Arms Dealing",
    "<suspect> Breaks Silence in Interogation",
    "<suspect> Issues Statement from Jail Cell, Proclaims Innocence",
    "Shocking Affair Exposed with <suspect>",
    " <suspect> Caught in Love Triangle with Celebrity Couple",
    "Paparazzi Capture <suspect> ",
    "<suspect> caught in Secret Romantic Getaway",
    "Scandal Rocks <cityName>",
    "<suspect> Accused of Cheating on Longtime Partner",
    "<suspect> Faces Backlash for Affair with Spouse of Ex",
    "<suspect> Spotted Leaving Hotel with Mystery Lover",
    "Breakup Drama: <suspect> Accused of Stealing Partner",
    "<suspect>'s Steamy Texts with Conspirators Leaked ",
    "<suspect>'s Romantic Liaisons Exposed",
    "<suspect> Details of Secret Relationships Revealed",
    "Couplecrisis: <suspect> and Partner's Marriage on the Rocks",
    "Reality Star <suspect> shits himself in public",
    "Gaming addiction of <suspect> exposed",
    "Love Scandal Unfolds with <suspect>",
    "<suspect> Accused of serial Infidelity by ex-Flames",
    "<suspect> and Famous Model date livestreamed",
    "Inside the Affair of <suspect>",
    "<suspect>'s Ex Speaks Out on Heartbreak and Betrayal",
    "Wedding Bells or Heartbreak? <suspect>",
    "<suspect> Engaged Amidst Cheating Allegations",
    "<suspect>'s Secret Love Letters Surface",
    "Public Outcry:  Reactions to <suspect>s fanfiction",
    "Hollywood's Hottest Scandal: <suspect>",
    "Not that good a player <suspect> dissed by opponents",
    "Infidelity Shockwave: <suspect> Accused of Cheating with Best Friend's Partner",
    "Paparazzi Stakeout: <suspect>'s Late-Night Rendezvous Raises Eyebrows",
    "<suspect> accused of virtual heist tactics.",
    "<suspect>'s gaming skills evident in Ponzi scheme.",
    "<suspect> fails to level up on tax evasion.",
    "<suspect>'s hacking resembles gaming.",
    "<suspect> attempts real estate cheat codes.",
    "Regulators slam <suspect>'s gaming-like investments.",
    "<suspect> uses boss fight tactics in fraud.",
    "<suspect> tries speedrun bank robbery.",
    "<suspect> relies on respawn for fraud.",
    "<suspect> fails game over evasion tactic.",
    "<suspect> is just not godde enough",
    "try spring classic",
    "recoil is the new spring",
    "Drama baby The community must life",
    "Buy <suspect> brand food",
    "Smoke <suspect> cosmetics",
    --todo more/better snappy slogans
    "Nota game <suspect>",
    "sell <suspect>s attention for adds",
    "Russindian orbitals ejects <suspect>",
    "Ifinite growth possible says <suspect>",
    "Bunkered down billionaires besieged in newzealandia",
    "Revolutionary Slogan Loading Error",
    "Millions dead in <cityName>",
    "Mercy not an option says <suspect>",
    "<suspect> gone gonzo says partner",
    "Try refreshing crack.",
    "In turbulent times survive with vilolent crimes INC",
    "Revolution resort to cannibalism after eating supply chain",
    "By the people for the people made of people",
    "Numb the Pain: NeuroVoid Serum",
"Suppress Emotions: TranquilTec Pills",
"Chemical Calm: SereniSedate Drops",
"Enhanced Endurance: BioBoost Boosters",
"Dreamless Sleep: SomniSilence Solution",
"Mind Control: NeuroCalm Capsules",
"Suppress Hunger: NutriNumb Formula",
"Zone Out: TranceTech Injections",
"Memory Erase: AmnesiaAmplify Dose",
"Body Modification: BioMorph Serum",
"Dulled Senses: SensorySuppressor",
"Chronic Fatigue Relief: EnduraEase Elixir",
"Psychological Detachment: PsychePurge Pills",
"DNA Alteration: GenoShift Injections",
"Life Extension: VitaVitality Formula",
"Neural Overdrive: NeuroZap Shots",
"Mind Control: ThoughtTwist Serum",
"Enhanced Obedience: CompliChip Implants",
"Cognition Suppression: MindMeld Suppressant",
"Organ Replacement: BioSynth Solutions",
"Regenerate or Rot: NecroCell Serum",
"Nerve Decay Halted: SynthNerve Vial",
"Mend Flesh: BioMend Nanogel",
"Purge Toxins: BioPurge Cleanser",
"Stem the Mutation: GenoStop Solution",
"Flesh Fusion: NanoFix Patch",
"Mind Over Mutation: PsyMeld Pills",
"Symbiotic Synapse: NeuroLink Injection",
"Vitality in a Vial: LifeLine Elixir",
"Suture Secrets: BioSeal Gel",
"Erase Decay: BioRebirth Serum",
"Bone Reinforcement: OsteoSteel Infusion",
"Reclaim Lost Limbs: SynthLim Prosthetics",
"DNA Redemption: GeneRevive Solution",
"Eternal Youth: AgeStop Therapy",
"Combat Decay: CellGuard Implants",
"Resurrect Vitality: Resilience Revive",
"Bio-Enhanced Recovery: NanoHeal Serum",
"Reject Disease: ImmunoRepel Injection",
"Embrace Evolution: MutateX Accelerator",
"Endless Vitality: ReanimaCell Program    ",
"Revive Dead Tissue: CorpseMeld Solution",
"Heal at Any Cost: NecroRegen Gel       ",
"Purify Your Body: BioPurge Serum       ",
" Extracted from the condemned",
"Stop Mutations: MutantEx Serum         ",
" A result of failed experiments",
"Repair with Precision: NanoFlesh Paste ",
"Master Your Mind: PsyHive Capsules     ",
"Extracted from unwilling donors",
"Link Your Neural Pathways: NeuroMerge Serum",
"Life's Essence: SoulElix Extract           ",
"Seal Wounds, Seal Fates: BioSeal Patch     ",
"Renew Your Bones: OsteoGrow Serum",
"Revive Lost Limbs: BioLimb Prosthetics",
"Rewrite Destiny: GeneForge Solution",
"Youth Reborn: AgeEx Serum",
"Guard Against Disease: ImmunoGuard Serum   ",
"Reclaim Your Health: LifeTrade Serum",
"Resurrect Lost Vitality: Rebirth Serum     ",
"Heal Faster: PainTrade Inject",
"Evolve or Die: MutateX Patch",
"Rise Again: Revenant Essence",
"Restore Sanity: ImplantEase Therapy",
"Implant Rehab: MindRevive Protocol ",
"Implant Malaise Cure: NeuralRestore Serum ",
"Mind Over Implant: NeuroReboot Treatment ",
"NeuroRepair: SynapseSoothe Therapy ",
"Implant Crisis Intervention: MindRescue Protocol",
"Implant Dysfunction Fix: NeuralSync Treatment ",
"Circuitry Correction: SynapseSavior Serum ",
"Implant Recovery Program: MindReset Protocol ",
"Implant Sanity Restoration: NeuroStabilize Therapy ",
"Neural Circuitry Repair: ImplantRevive Serum",
"Implant Harmony Solution: SynapseSync Therapy ",
"Implant Overload Relief: NeuralRelief Protocol ",
"Neural Implant Rebalance: MindBalance Treatment ",
"Implant Dysfunction Remedy: SynapseRestore Serum ",
"Implant Crisis Management: MindCrisis Protocol ",
"Neurological Reconstruction: ImplantRebuild Therapy ",
"Implant Catastrophe Recovery: SynapseRecovery Serum ",
"Implant Dissonance Eradication: NeuralHarmony Treatment ",
"Implant Anomaly Correction: MindFix Protocol ",
"<suspect> marries Nigerian Prince",
"The shaft ! True Penis prolonging",
"Buy! Consume! Die!",
"Outrageous atrocity by other empire",
"Heroic actons taken by our empire",
"Subverted Subversion found in Institution",
"Third Responsibilityrevolution",
"Corruption huntsmen bring back head of company",
"DAO Droneswarm piracy returns",
"Donate to starving preppers",
"Medlle east goes madmax again",
"Annual purge coming up",
"Memetic disease awareness month",
"Geezer Gonoreha Not for all money in the world",
"Moon colonies putting spring in your step",
"You cant just write an shit",
"File not found",
"Rest API unresolved error",
"Shameless smut citywide",

-- 3d model holograms house_asian_hologram
-- spinable rouletttable
-- basketball rotating, falling in
}