-- Generated by tools/civic_objectives/generate.py.
return {
    {name="objective_prison", title="Prison Megablock", description="Detention blocks and civic administration", height=39},
    {name="objective_hospital", title="Hospital Arcology", description="Medical wards, emergency care and staff housing", height=54},
    {name="objective_university", title="University Megaproject", description="Teaching, research and student housing", height=60},
    {name="objective_recycling", title="Recycling and Housing", description="Municipal materials recovery and worker housing", height=50},
    {name="objective_courthouse", title="Courthouse and Archive", description="Civil courts and public records", height=61},
    {name="objective_market", title="Wholesale Food Exchange", description="Covered markets and refrigerated distribution", height=46},
    {name="objective_cemetery", title="Vertical Cemetery", description="Columbarium towers and memorial gardens", height=69},
    {name="objective_fire_rescue", title="Fire and Rescue Complex", description="Emergency services and training campus", height=44},
}
