-- Generated by tools/civic_objectives/generate.py; Y-up, origin at ground.
return {
    radius = 93, height = 61, midpos = {0, 30.5, 0},
    tex1 = "house_asian_diffuse.dds",
    tex2 = "house_asian_selfilu_reflection.png",
}
